import { expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import path from "node:path"

const ROOT = path.resolve(import.meta.dir, "..")
const REPO_ROOT = path.resolve(ROOT, "../..")

function readText(rel: string): string {
  return readFileSync(path.join(ROOT, rel), "utf8")
}

function readRepo(rel: string): string {
  return readFileSync(path.join(REPO_ROOT, rel), "utf8")
}

test("browser preview panel uses mature primitives and task evidence-backed service", () => {
  const component = readText("src/components/BrowserPreviewPanel.tsx")
  const service = readText("src/services/browser-preview.ts")
  const html = readText("src/index.html")
  const main = readText("src/main.tsx")
  const css = readText("src/styles/surfaces/inspector.css")
  const activityCss = readText("src/styles/surfaces/activity.css")

  expect(html).toContain('id="chatViewTitle"')
  expect(html).toContain('id="centerWorkbenchBrowser"')
  expect(html).toContain('id="solidBrowserPreviewMount"')
  expect(html).not.toContain('id="rightPanelBrowser"')
  expect(html).not.toContain('id="solidRightPanelTabs"')
  expect(main).toContain("<BrowserPreviewPanel")
  expect(main).toContain('active={() => isCenterWorkbenchPanelOpen("browser")}')
  expect(main).toContain("browserPreviewLinkRefresh")
  expect(main).toContain('refreshKey={() => `${boardStore.boardUpdatedAt}:${browserPreviewLinkRefresh()}`}')
  expect(main).toContain("function openRightActivity(activity: RightActivity): void")
  expect(main).toContain("openCenterWorkbenchPanel(activity)")
  expect(main).toContain('onReady={() => openRightActivity("browser")}')
  expect(main).not.toContain("saveTaskBrowserPreviewTarget")
  expect(main).toContain('anchor.getAttribute("data-browser-preview-url")')
  expect(main).toContain("openBrowserPreviewFromMessage()")
  expect(main).not.toContain("openBrowserPreviewUrl(previewUrl)")
  expect(main).not.toContain('onReady={() => selectRightActivity("browser")}')
  expect(main).toContain('browser: document.getElementById("centerWorkbenchBrowser")')
  expect(main).toContain("onSelect={selectRightActivity}")

  expect(component).toContain('from "./ui/Tabs"')
  expect(component).toContain('from "./ui/Button"')
  expect(component).toContain('from "@kobalte/core/select"')
  expect(component).toContain("currentTarget()?.viewports")
  expect(component).toContain("currentTarget()?.candidates")
  expect(component).toContain("selectedCandidate")
  expect(component).toContain("loadTaskBrowserPreviewTarget")
  expect(component).toContain("selectTaskBrowserPreviewTarget")
  expect(component).toContain("targetID: candidate.id")
  expect(component).not.toContain("draftUrl")
  expect(component).not.toContain("setDraftUrl")
  expect(component).not.toContain("submitUrl")
  expect(component).toContain("captureTaskBrowserPreviewEvidence")
  expect(component).toContain("loadTaskBrowserPreviewEvidence")
  expect(component).toContain("loadTaskBrowserPreviewEvidenceCaptureObjectUrl")
  expect(component).toContain("renderedEvidence")
  expect(component).toContain("captureImageUrl")
  expect(component).toContain('data-ui="browser-preview-screenshot"')
  expect(component).toContain("verificationRequest()")
  expect(component).toContain("latestEvidenceID")
  expect(component).toContain("evidenceFromVerification")
  expect(component).toContain("scope: { taskID: string; targetID: string }")
  expect(component).toContain("targetID: scope.targetID")
  expect(component).not.toContain('input.target.id ?? ""')
  expect(component).not.toContain('input.target.taskID ?? ""')
  expect(component).not.toContain('input.target.id ?? "target"')
  expect(component).toContain("viewportIDs")
  expect(component).toContain("viewports().map((viewport) => viewport.id)")
  expect(component).toContain("props.refreshKey()")
  expect(component).toContain("props.onReady?.(resolved)")
  expect(component).toContain("lastAutoFocusedPreviewKey")
  expect(component).toContain("data-active={String(panelActive())}")
  expect(component).toContain("browser-preview-command-surface")
  expect(component).toContain("browser-preview-controls")
  expect(component).toContain('data-status="missing"')
  expect(component).toContain('t("browser_preview.status.missing")')
  expect(component).toContain("browser-preview-candidate-select")
  expect(component).toContain("<Select.Root")
  expect(component).toContain("<Select.Trigger")
  expect(component).toContain("<Select.Listbox")
  expect(component).toContain("BrowserPreviewCandidateOption")
  expect(component).toContain("browser-preview-viewport-controls")
  expect(component).toContain('data-orientation="horizontal"')
  expect(component).toContain("onValueChange={(value) => setViewportID(value as BrowserPreviewViewportID)}")
  expect(component).not.toContain("onClick={() => setViewportID(item.id)}")
  expect(component).not.toContain("browser-preview-viewport-layout")
  expect(component).not.toContain("browser-preview-viewport-tab-row")
  expect(component).not.toContain("browser-preview-visibility-toggles")
  expect(component).not.toContain("browser-preview-viewport-toggle")
  expect(component).not.toContain("browser_preview.viewport.toggle")
  expect(component).toContain('data-ui="browser-preview-evidence"')
  expect(component).toContain('data-ui="browser-preview-evidence-missing"')
  expect(component).toContain("browser-preview-evidence-facts")
  expect(component).not.toContain("<select")
  expect(component).not.toContain("<iframe")
  expect(component).not.toContain("frameUrl")
  expect(component).toContain("const targetUrl = createMemo(() => currentTarget()?.url)")
  expect(component).not.toMatch(/src=\{?frameUrl/)
  expect(component).not.toContain("window.open")
  expect(component).not.toContain("data-frame-token")
  expect(component).not.toContain("sandbox=")
  expect(component).not.toContain("referrerPolicy=")
  expect(component).not.toContain("getHostTransport")
  expect(component).not.toContain("canEmbedPreviewFrame")
  expect(component).not.toContain("embeddableFrameUrl")
  expect(component).not.toContain("browser-preview-host-blocked")
  expect(component).toContain("props.taskID()")
  expect(component).toContain("props.active()")
  expect(component).not.toContain("!props.active() || !taskID || !directory")
  expect(component).toContain("currentTargetError")
  expect(component).toContain('data-status="failed"')
  expect(component).toContain('verification.error ? "failed"')
  expect(component).not.toContain("new EventSource")
  expect(component).not.toContain("fetch(")
  expect(component).not.toContain("window.setInterval")
  expect(component).toContain('class="browser-preview-evidence"')
  expect(service).toContain("apiJson(`task/${encodeURIComponent(taskID)}/browser-preview`")
  expect(service).toContain("apiJson(`task/${encodeURIComponent(input.taskID)}/browser-preview/target`")
  expect(service).toContain("targetID: input.targetID")
  expect(service).toContain("viewportIDs: input.viewportIDs")
  expect(service).not.toContain("viewportID: input.viewportID")
  expect(service).not.toContain("url: input.url")
  expect(service).toContain("apiJson(`task/${encodeURIComponent(input.taskID)}/browser-preview/capture`")
  expect(service).toContain('responseKind: "binary"')
  expect(service).toContain("capture.png")
  expect(service).not.toContain("apiJson(`browser-preview")
  expect(service).not.toContain("fetch(")
  expect(service).not.toContain("captureRuntimePage")
  expect(service).not.toContain("renderPage")
  expect(service).not.toContain("BrowserEvidenceRunner")
  expect(service).not.toContain("BROWSER_PREVIEW_VIEWPORTS")

  expect(activityCss).toContain(".chat-browser-preview-activity")
  expect(css).toContain(".browser-preview-panel")
  expect(css).toContain("container: browser-preview / inline-size")
  expect(css).toContain(".browser-preview-command-surface")
  expect(css).toContain(".browser-preview-controls")
  expect(css).toContain(".browser-preview-candidate-select")
  expect(css).toContain(".browser-preview-candidate-trigger")
  expect(css).toContain(".browser-preview-candidate-content")
  expect(css).toContain(".browser-preview-candidate-option")
  expect(css).not.toContain(".browser-preview-url-field")
  expect(css).not.toContain(".browser-preview-candidate-select select")
  expect(css).toContain("min-height: calc(28px * var(--ui-scale))")
  expect(css).toContain("@container browser-preview (max-width: 280px)")
  expect(css).toContain(".browser-preview-viewport-controls")
  expect(css).not.toContain(".browser-preview-viewport-layout")
  expect(css).not.toContain(".browser-preview-viewport-tab-row")
  expect(css).not.toContain(".browser-preview-visibility-toggles")
  expect(css).not.toContain(".browser-preview-viewport-toggle")
  expect(css).not.toContain(".browser-preview-frame-grid")
  expect(css).not.toContain(".browser-preview-frame-header")
  expect(css).not.toContain(".browser-preview-frame-actions")
  expect(css).not.toContain(".browser-preview-frame")
  expect(css).not.toContain('.browser-preview-empty[data-status="host-blocked"]')
  expect(css).toContain(".browser-preview-evidence {")
  expect(css).toContain(".browser-preview-evidence-shot")
  expect(css).toContain(".browser-preview-evidence-header")
  expect(css).toContain(".browser-preview-evidence-facts")
  expect(css).toContain(".browser-preview-evidence-status")
  expect(css).toContain("place-items: center")
})

test("VS Code preview contract is evidence-backed under frame-src none", () => {
  const component = readText("src/components/BrowserPreviewPanel.tsx")
  const service = readText("src/services/browser-preview.ts")
  const vscodeWebview = readRepo("packages/vscode-extension/src/webview/html.ts")

  expect(vscodeWebview).toContain("frame-src 'none'")
  expect(component).not.toContain("<iframe")
  expect(component).not.toContain("sandbox=")
  expect(component).not.toContain("referrerPolicy=")
  expect(component).not.toContain("canEmbedPreviewFrame")
  expect(component).not.toContain("browser-preview-host-blocked")
  expect(component).toContain('data-ui="browser-preview-evidence"')
  expect(component).toContain('data-ui="browser-preview-evidence-missing"')
  expect(component).toContain('aria-label={t("browser_preview.capture_title")}')
  expect(component).toContain("captureTaskBrowserPreviewEvidence")
  expect(component).toContain('data-ui="browser-preview-screenshot"')
  expect(service).toContain("targetID: input.targetID")
  expect(service).toContain("viewportIDs: input.viewportIDs")
  expect(service).toContain('responseKind: "binary"')
})
