import { expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import path from "node:path"

const ROOT = path.resolve(import.meta.dir, "..")
const REPO_ROOT = path.resolve(ROOT, "../..")

function readText(rel: string): string {
  return readFileSync(path.join(ROOT, rel), "utf8")
}

function readRepo(rel: string): string {
  return readFileSync(path.join(REPO_ROOT, rel), "utf8")
}

test("browser preview panel uses native WebView surface with task evidence as the data source", () => {
  const component = readText("src/components/BrowserPreviewPanel.tsx")
  const service = readText("src/services/browser-preview.ts")
  const nativeService = readText("src/services/browser-preview-native.ts")
  const hostTransport = readText("src/services/host-transport.ts")
  const tauriTransport = readText("src/services/tauri-transport.ts")
  const html = readText("src/index.html")
  const main = readText("src/main.tsx")
  const css = readText("src/styles/surfaces/inspector.css")
  const tauriMain = readText("src-tauri/src/main.rs")
  const tauriCargo = readText("src-tauri/Cargo.toml")

  expect(html).toContain('id="centerWorkbenchBrowser"')
  expect(html).toContain('id="solidBrowserPreviewMount"')
  expect(main).toContain("<BrowserPreviewPanel")
  expect(main).toContain('active={() => isCenterWorkbenchPanelOpen("browser")}')
  expect(main).toContain("browserPreviewLinkRefresh")
  expect(main).toContain("refreshKey={() => `${boardStore.boardUpdatedAt}:${browserPreviewLinkRefresh()}`}")
  expect(main).toContain('onReady={() => openRightActivity("browser")}')

  expect(component).toContain("loadTaskBrowserPreviewTarget")
  expect(component).toContain("selectTaskBrowserPreviewTarget")
  expect(component).toContain("captureTaskBrowserPreviewEvidence")
  expect(component).toContain("loadTaskBrowserPreviewEvidence")
  expect(component).toContain("loadTaskBrowserPreviewEvidenceCaptureObjectUrl")
  expect(component).toContain("nativePreviewScope")
  expect(component).toContain("syncBrowserPreviewNativeSurface")
  expect(component).toContain("navigateBrowserPreviewNativeSurface")
  expect(component).toContain("closeBrowserPreviewNativeSurface")
  expect(component).toContain("browserPreviewNativeElementBounds")
  expect(component).toContain('data-ui="browser-preview-native-surface"')
  expect(component).toContain('data-ui="browser-preview-navigation-controls"')
  expect(component).toContain('onClick={() => navigateNativePreview("back")}')
  expect(component).toContain('onClick={() => navigateNativePreview("forward")}')
  expect(component).toContain('onClick={() => navigateNativePreview("reload")}')
  expect(component).toContain('imageDataUI="browser-preview-screenshot"')
  expect(component).toContain("<PreviewableImage")
  expect(component).toContain("<SelectControl<BrowserPreviewCandidate>")
  expect(component).toContain("<SegmentedControl<BrowserPreviewViewportID>")

  expect(component).not.toContain("loadTaskBrowserPreviewLiveSnapshotObjectUrl")
  expect(component).not.toContain("sendTaskBrowserPreviewLiveInputsObjectUrl")
  expect(component).not.toContain("BrowserPreviewLiveInput")
  expect(component).not.toContain("PendingBrowserPreviewLiveInput")
  expect(component).not.toContain("browserPreviewLivePoint")
  expect(component).not.toContain('data-ui="browser-preview-live-screenshot"')
  expect(component).not.toContain("browser-preview-live-frame")
  expect(component).not.toContain("liveFrameStyle")
  expect(component).not.toContain("--browser-preview-live-aspect-ratio")
  expect(component).not.toContain("<iframe")
  expect(component).not.toContain("sandbox=")
  expect(component).not.toContain("referrerPolicy=")
  expect(component).not.toContain("draftUrl")
  expect(component).not.toContain("setDraftUrl")
  expect(component).not.toContain("submitUrl")
  expect(component).not.toContain("window.open")
  expect(component).not.toContain("getHostTransport")

  expect(service).toContain("function taskBrowserPreviewPath(taskID: string, directory: string")
  expect(service).toContain("loadTaskBrowserPreviewTarget(input: {")
  expect(service).toContain("selectTaskBrowserPreviewTarget(input: {")
  expect(service).toContain("captureTaskBrowserPreviewEvidence(input: {")
  expect(service).toContain("loadTaskBrowserPreviewEvidence(input: {")
  expect(service).toContain("loadTaskBrowserPreviewEvidenceCaptureObjectUrl(input: {")
  expect(service).toContain('taskBrowserPreviewPath(input.taskID, input.directory, "/capture")')
  expect(service).toContain('responseKind: "binary"')
  expect(service).not.toContain("BrowserPreviewLiveInput")
  expect(service).not.toContain("loadTaskBrowserPreviewLiveSnapshotObjectUrl")
  expect(service).not.toContain("sendTaskBrowserPreviewLiveInputsObjectUrl")
  expect(service).not.toContain('"/live/snapshot"')
  expect(service).not.toContain('"/live/input"')
  expect(service).not.toContain("url: input.url")

  expect(nativeService).toContain("const REQUIRED_BROWSER_PREVIEW_COMMANDS")
  expect(nativeService).toContain('"browserPreview.sync"')
  expect(nativeService).toContain('"browserPreview.navigate"')
  expect(nativeService).toContain('"browserPreview.close"')
  expect(nativeService).toContain("getHostTransport().capabilities.nativeCommands")
  expect(nativeService).toContain('kind: "browserPreview.sync"')
  expect(nativeService).toContain('kind: "browserPreview.navigate"')
  expect(nativeService).toContain('kind: "browserPreview.close"')

  expect(hostTransport).toContain('"browserPreview.sync": true')
  expect(hostTransport).toContain('"browserPreview.navigate": true')
  expect(hostTransport).toContain('"browserPreview.close": true')
  expect(tauriTransport).toContain('invokeTauri("overlay_browser_preview_sync"')
  expect(tauriTransport).toContain('invokeTauri("overlay_browser_preview_navigate"')
  expect(tauriTransport).toContain('invokeTauri("overlay_browser_preview_close"')

  expect(tauriCargo).toContain('features = ["tray-icon", "unstable"]')
  expect(tauriMain).toContain('const BROWSER_PREVIEW_WEBVIEW_LABEL: &str = "browser-preview-live-webview";')
  expect(tauriMain).toContain("overlay_browser_preview_sync")
  expect(tauriMain).toContain("tauri::webview::WebviewBuilder")
  expect(tauriMain).toContain(".add_child(builder, position, size)")
  expect(tauriMain).toContain(".navigate(target_url)")
  expect(tauriMain).toContain("overlay_browser_preview_navigate")
  expect(tauriMain).toContain('Some("history.back();")')
  expect(tauriMain).toContain('Some("history.forward();")')
  expect(tauriMain).toContain("webview.reload()")
  expect(tauriMain).toContain("overlay_browser_preview_close")
  expect(tauriMain).toContain("webview.hide()")

  expect(css).toContain(".browser-preview-browser-controls")
  expect(css).toContain(".browser-preview-live")
  expect(css).toContain(".browser-preview-native-surface")
  expect(css).toContain("min-height: 100%")
  expect(css).not.toContain(".browser-preview-live-frame")
  expect(css).not.toContain("aspect-ratio: var(--browser-preview-live-aspect-ratio)")
  expect(css).not.toContain(".browser-preview-live-frame img")
})

test("VS Code preview contract remains evidence-backed under frame-src none", () => {
  const component = readText("src/components/BrowserPreviewPanel.tsx")
  const nativeService = readText("src/services/browser-preview-native.ts")
  const vscodeWebview = readRepo("packages/vscode-extension/src/webview/html.ts")
  const bridge = readRepo("packages/vscode-extension/src/transport/bridge.ts")

  expect(vscodeWebview).toContain("frame-src 'none'")
  expect(component).not.toContain("<iframe")
  expect(component).not.toContain("sandbox=")
  expect(component).not.toContain("referrerPolicy=")
  expect(component).toContain('data-ui="browser-preview-evidence"')
  expect(component).toContain('data-ui="browser-preview-native-surface"')
  expect(component).toContain("captureTaskBrowserPreviewEvidence")
  expect(component).toContain('imageDataUI="browser-preview-screenshot"')
  expect(nativeService).toContain("UnsupportedNativeCommandError")
  expect(bridge).toContain('Native command "${command.kind}" is not available in the VS Code host.')
})
