import { expect, test } from "bun:test"
import { existsSync, readFileSync } from "node:fs"
import path from "node:path"

const ROOT = path.resolve(import.meta.dir, "..")

function readText(rel: string): string {
  return readFileSync(path.join(ROOT, rel), "utf8")
}

test("chat view TUI tab is the project-bound OpenTUI runtime activity", () => {
  const panel = readText("src/plugins/coding-agent-tui/CodingAgentTuiPanel.tsx")
  const service = readText("src/plugins/coding-agent-tui/embedded-target.ts")
  const plugin = readText("src/plugins/coding-agent-tui/index.tsx")
  const html = readText("src/index.html")
  const main = readText("src/main.tsx")
  const css = readText("src/styles/surfaces/activity.css")

  expect(html).toContain('id="solidChatViewTabs"')
  expect(html).toContain('id="chatTuiPane"')
  expect(html).toContain('id="solidTuiHostMount"')
  expect(html).toContain('data-right-activity="inspector"')
  expect(html).not.toContain('id="solidRightPanelTabs"')
  expect(html).not.toContain('id="rightPanelTui"')
  expect(html).not.toContain('id="rightPanelAssistant"')
  expect(html).not.toContain('id="solidCodingAssistantMount"')

  expect(main).toContain('type ChatView = "conversation" | typeof codingAgentTuiPlugin.id | "browser"')
  expect(main).toContain('const DEFAULT_CHAT_VIEW: ChatView = "conversation"')
  expect(main).toContain('const DEFAULT_RIGHT_ACTIVITY: RightActivity = "inspector"')
  expect(main).toContain('import { codingAgentTuiPlugin } from "./plugins/coding-agent-tui"')
  expect(main).toContain("CHAT_VIEWS")
  expect(main).toContain("const CodingAgentTuiPanel = codingAgentTuiPlugin.Panel")
  expect(main).toContain("chatView() === codingAgentTuiPlugin.id")
  expect(main).toContain("directory={activeDirectory}")
  expect(main).not.toContain("<TuiHostPanel")
  expect(plugin).toContain('id: CODING_AGENT_TUI_ACTIVITY_ID')
  expect(plugin).toContain('bodyId: "chatTuiPane"')
  expect(plugin).toContain('mountId: "solidTuiHostMount"')
  expect(main).toContain('document.getElementById("solidChatViewTabs")')
  expect(main).toContain('document.getElementById("chatTuiPane")')
  expect(main).not.toContain("<CodingAssistantPanel")
  expect(main).not.toContain("rightPanelTab")
  expect(main).not.toContain("TuiRuntimePanel")

  expect(panel).toContain("props.active()")
  expect(panel).toContain("props.directory().trim()")
  expect(panel).toContain('from "./embedded-target"')
  expect(panel).toContain("frame().lines")
  expect(panel).toContain("spanStyle(span, line)")
  expect(panel).toContain("sendTuiEmbedInput({ ...payload, directory: hostDirectory() })")
  expect(panel).not.toContain('import("ghostty-web")')
  expect(panel).not.toContain("new mod.Terminal")
  expect(panel).not.toContain("createTuiHostConnectToken")
  expect(panel).not.toContain("new WebSocket")
  expect(panel).not.toContain("socket.send(data)")
  expect(panel).not.toContain("sendTuiHostInput(data)")
  expect(panel).not.toContain("loadTuiHostOutput(hostCursor)")
  expect(panel).not.toContain("loadTuiHostSnapshot")
  expect(panel).toContain('aria-label={t("tui.title")}')
  expect(panel).not.toContain("new EventSource")
  expect(panel).not.toContain("fetch(")
  expect(service).toContain('apiJson(tuiPath("tui/embed/start", input.directory)')
  expect(service).toContain('apiJson(tuiPath("tui/embed/input", input.directory)')
  expect(service).toContain('apiJson(tuiPath("tui/embed/resize", input.directory)')
  expect(service).toContain('params.set("directory", requireDirectory(directory))')
  expect(service).toContain("agent: TUI_CODING_AGENT")
  expect(service).not.toContain("apiWebSocketUrl")
  expect(service).not.toContain('pty"')
  expect(service).not.toContain("connect-token")
  expect(service).not.toContain("x-opencode-ticket")
  expect(service).not.toContain("tui/host")
  expect(service).not.toContain('apiJson("tui/host/input"')
  expect(service).not.toContain('apiJson("tui/host/snapshot"')
  expect(service).not.toContain('apiJson(`tui/host/output')
  expect(service).not.toContain('apiJson("tui/host/resize"')
  expect(service).not.toContain("tui/runtime/status")
  expect(css).toContain(".side-activity-toolbar")
  expect(css).toContain(".chat-tui-activity")
  expect(css).toContain(".tui-host-panel")
  expect(css).toContain(".tui-host-terminal")
})

test("retired browser-side coding assistant service does not remain as a right-sidebar TUI double source", () => {
  expect(existsSync(path.join(ROOT, "src/services/coding-assistant.ts"))).toBe(false)
  expect(existsSync(path.join(ROOT, "src/services/coding-assistant-transcript.ts"))).toBe(false)
  expect(existsSync(path.join(ROOT, "src/components/TuiHostPanel.tsx"))).toBe(false)
  expect(existsSync(path.join(ROOT, "src/services/tui-host.ts"))).toBe(false)
  expect(existsSync(path.join(ROOT, "src/services/tui-host-terminal.ts"))).toBe(false)
  expect(existsSync(path.join(ROOT, "src/plugins/coding-agent-tui/pty-target.ts"))).toBe(false)
  expect(existsSync(path.join(ROOT, "test/coding-assistant-service.test.ts"))).toBe(false)
})
