import { expect, test } from "bun:test"
import { existsSync, readFileSync } from "node:fs"
import path from "node:path"

const ROOT = path.resolve(import.meta.dir, "..")

function readText(rel: string): string {
  return readFileSync(path.join(ROOT, rel), "utf8")
}

test("right side coding assistant entry is the project-bound OpenTUI runtime activity", () => {
  const panel = readText("src/plugins/coding-agent-tui/CodingAgentTuiPanel.tsx")
  const service = readText("src/plugins/coding-agent-tui/pty-target.ts")
  const plugin = readText("src/plugins/coding-agent-tui/index.tsx")
  const toolbar = readText("src/components/SideActivityToolbar.tsx")
  const html = readText("src/index.html")
  const main = readText("src/main.tsx")
  const css = readText("src/styles/surfaces/activity.css")

  expect(html).toContain('id="solidRightActivityToolbar"')
  expect(html).toContain('id="rightPanelTui"')
  expect(html).toContain('id="solidTuiHostMount"')
  expect(html).toContain('data-right-activity="inspector"')
  expect(html).not.toContain('id="solidRightPanelTabs"')
  expect(html).not.toContain('id="rightPanelAssistant"')
  expect(html).not.toContain('id="solidCodingAssistantMount"')

  expect(main).toContain('type RightActivity = typeof codingAgentTuiPlugin.id | "browser" | "inspector"')
  expect(main).toContain('const DEFAULT_RIGHT_ACTIVITY: RightActivity = "inspector"')
  expect(main).toContain('import { codingAgentTuiPlugin } from "./plugins/coding-agent-tui"')
  expect(main).toContain("codingAgentTuiPlugin.activity")
  expect(main).toContain("const CodingAgentTuiPanel = codingAgentTuiPlugin.Panel")
  expect(main).toContain("rightActivity() === codingAgentTuiPlugin.id")
  expect(main).toContain("directory={activeDirectory}")
  expect(main).not.toContain("<TuiHostPanel")
  expect(plugin).toContain('id: CODING_AGENT_TUI_ACTIVITY_ID')
  expect(plugin).toContain('bodyId: "rightPanelTui"')
  expect(plugin).toContain('mountId: "solidTuiHostMount"')
  expect(main).toContain('document.getElementById("solidRightActivityToolbar")')
  expect(main).toContain("document.getElementById(codingAgentTuiPlugin.bodyId)")
  expect(main).not.toContain("<CodingAssistantPanel")
  expect(main).not.toContain("rightPanelTab")
  expect(main).not.toContain("TuiRuntimePanel")

  expect(panel).toContain("props.active()")
  expect(panel).toContain("props.directory().trim()")
  expect(panel).toContain('import("ghostty-web")')
  expect(panel).toContain("new mod.Terminal")
  expect(panel).not.toContain("createTuiHostConnectToken")
  expect(panel).toContain("new WebSocket(buildTuiHostConnectUrl")
  expect(panel).toContain("socket.send(data)")
  expect(panel).toContain("resizeTuiHost({ id, cols, rows, directory: hostDirectory() })")
  expect(panel).not.toContain("sendTuiHostInput(data)")
  expect(panel).not.toContain("loadTuiHostOutput(hostCursor)")
  expect(panel).not.toContain("loadTuiHostSnapshot")
  expect(panel).toContain('aria-label={t("tui.title")}')
  expect(panel).not.toContain("new EventSource")
  expect(panel).not.toContain("fetch(")
  expect(service).toContain('apiJson(ptyPath("pty", input.directory)')
  expect(service).toContain("apiWebSocketUrl(ptyPath(`pty/${encodeURIComponent(input.id)}/connect")
  expect(service).toContain('params.set("directory", requireDirectory(directory))')
  expect(service).toContain('OPENCORVUS_OVERLAY_TUI_PLUGIN: "coding-agent-tui"')
  expect(service).not.toContain("connect-token")
  expect(service).not.toContain("x-opencode-ticket")
  expect(service).not.toContain("tui/host")
  expect(service).not.toContain('apiJson("tui/host/input"')
  expect(service).not.toContain('apiJson("tui/host/snapshot"')
  expect(service).not.toContain('apiJson(`tui/host/output')
  expect(service).not.toContain('apiJson("tui/host/resize"')
  expect(service).not.toContain("tui/runtime/status")
  expect(toolbar).toContain('data-ui="side-activity-button"')
  expect(css).toContain(".side-activity-toolbar")
  expect(css).toContain(".tui-host-panel")
  expect(css).toContain(".tui-host-terminal")
})

test("retired browser-side coding assistant service does not remain as a right-sidebar TUI double source", () => {
  expect(existsSync(path.join(ROOT, "src/services/coding-assistant.ts"))).toBe(false)
  expect(existsSync(path.join(ROOT, "src/services/coding-assistant-transcript.ts"))).toBe(false)
  expect(existsSync(path.join(ROOT, "src/components/TuiHostPanel.tsx"))).toBe(false)
  expect(existsSync(path.join(ROOT, "src/services/tui-host.ts"))).toBe(false)
  expect(existsSync(path.join(ROOT, "src/services/tui-host-terminal.ts"))).toBe(false)
  expect(existsSync(path.join(ROOT, "test/coding-assistant-service.test.ts"))).toBe(false)
})
