import { expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"

test("ConversationAgentRail reads hydrated workflow records and renders adjacent identity stacks", () => {
  const source = readFileSync(join(import.meta.dir, "../src/components/ConversationAgentRail.tsx"), "utf8")
  expect(source).toContain("conversationAgentRecordsForSource(boardStore.selectedSource)")
  expect(source).toContain("buildAdjacentAgentRailStacks(records())")
  expect(source).toContain("previous?.stage === stage")
  expect(source).toContain('class="conversation-agent-rail__stack"')
  expect(source).not.toContain("buildAgentWorkflow(")
  expect(source).not.toContain("mergeAgentRecords")
  expect(source).not.toContain("orderedReachableCardIDs()")
  expect(source).not.toContain("Object.values(cardTreeStore.cards).find")
  expect(source).toContain("Index")
  expect(source).not.toContain("compactAgentWorkflowLanesForNarrowRail")
  expect(source).not.toContain("LaneAvatarStack")
  expect(source).not.toContain("buildAgentWorkflowLanes")
  expect(source).not.toContain("<For each={records()}>")
  expect(source).not.toContain("payload.report")
  expect(source).not.toContain("event.kind")
})

test("ConversationAgentRail locate ticks use Button plus Kobalte tooltip summaries", () => {
  const source = readFileSync(join(import.meta.dir, "../src/components/ConversationAgentRail.tsx"), "utf8")
  const css = readFileSync(join(import.meta.dir, "../src/styles/surfaces/conversation.css"), "utf8")
  expect(source).toContain('import * as Tooltip from "@kobalte/core/tooltip"')
  expect(source).toContain('import { Button } from "./ui/Button"')
  expect(source).toContain("<Tooltip.Root")
  expect(source).toContain("as={Button}")
  expect(source).toContain('data-ui="conversation-agent-rail-locate"')
  expect(source).toContain("aria-label={tooltipLabel()}")
  expect(source).toContain("title={tooltipLabel()}")
  expect(source).toContain("agentRailSummary(record)")
  expect(source).toContain("record.displaySummary?.text ||")
  expect(source).not.toContain("record.traceReport?.summary")
  expect(source).toContain('t("agent_rail.detail.summary"')
  expect(source).toContain("AGENT_RAIL_STATUS_LABELS")
  expect(source).toContain('t("agent_rail.status.running")')
  expect(source).toContain('t("agent_rail.attempt"')
  expect(source).not.toContain("record.status]")
  expect(source).not.toContain("`V${record.attempt}`")
  expect(source).not.toContain("<button")
  expect(source).not.toContain("conversation-agent-rail__avatar-button")
  expect(css).toContain('.conversation-agent-rail .oc-button[data-ui="conversation-agent-rail-locate"]')
  expect(css).toContain(".conversation-agent-rail-tooltip")
  expect(css).toContain(".conversation-agent-rail__tick-line")
  expect(css).not.toContain(".conversation-agent-rail__avatar-button")
  expect(css).not.toMatch(/conversation-agent-rail[^{]*\{[^}]*appearance:\s*none/)
})

test("ConversationAgentRail locates cards through renderedCardID and CSS.escape", () => {
  const source = readFileSync(join(import.meta.dir, "../src/components/ConversationAgentRail.tsx"), "utf8")
  expect(source).toContain("record.renderedCardID")
  expect(source).toContain("record.targetMessageID")
  expect(source).toContain("conversationCardContainsMessage")
  expect(source).toContain("loadConversationSessionHistory")
  expect(source).toContain("materializeRecordTarget")
  expect(source).toContain("currentRecordForSession")
  expect(source).toContain("messageID: targetMessageID")
  expect(source).toContain("CSS.escape(targetRecord.renderedCardID")
  expect(source).toContain("setCardExpanded(targetRecord.renderedCardID, true")
  expect(source).toContain("setCardExpanded(parentID, true")
  expect(source).toContain("requestConversationCardScroll")
  expect(source).toContain('t("agent_rail.card_unavailable_title")')
  expect(source).toContain('t("agent_rail.no_rendered_card_target"')
  expect(source).toContain('t("agent_rail.rendered_card_missing"')
  expect(source).not.toContain("Agent card unavailable")
  expect(source).not.toContain("has no rendered conversation card target")
  expect(source).not.toContain("could not be located in the conversation")
  expect(source).toContain('focus: "header"')
  expect(source).toContain("highlight: true")
  expect(source).not.toContain('scrollIntoView({ block: "center"')
})

test("Conversation card-scroll waits for virtualized target materialization", () => {
  const source = readFileSync(join(import.meta.dir, "../src/components/Conversation.tsx"), "utf8")
  expect(source).toContain("CARD_SCROLL_TARGET_MAX_FRAMES")
  expect(source).toContain("waitForScrollTargetElement")
  expect(source).toContain("const target = await waitForScrollTargetElement(request)")
  expect(source).not.toContain(
    "await waitForAnimationFrame();\n    await waitForAnimationFrame();\n    const target = scrollTargetElement(request)",
  )
})

test("ConversationAgentRail stays a fixed narrow left rail inside the message pane", () => {
  const source = readFileSync(join(import.meta.dir, "../src/components/ConversationAgentRail.tsx"), "utf8")
  const css = readFileSync(join(import.meta.dir, "../src/styles/surfaces/conversation.css"), "utf8")
  const html = readFileSync(join(import.meta.dir, "../src/index.html"), "utf8")
  expect(source).not.toContain("--conversation-agent-rail-height")
  expect(source).not.toContain("startY - move.clientY")
  expect(source).not.toContain("attachRailDragScroll")
  expect(source).not.toContain("data-wide")
  expect(source).not.toContain("--conversation-agent-rail-width")
  expect(css).toContain("border-right: 0 solid transparent")
  expect(css).toContain("background: transparent;")
  expect(css).toContain("box-shadow: none;")
  expect(css).toContain("flex: 0 0 calc(46px * var(--ui-scale))")
  expect(css).toContain("width: calc(46px * var(--ui-scale))")
  expect(css).toContain("--conversation-message-lane-width: calc(920px * var(--ui-scale));")
  expect(css).toContain("width: min(100%, var(--conversation-message-lane-width));")
  expect(css).toContain("align-items: center;")
  expect(css).toContain("height: 100%")
  expect(css).toContain("flex-direction: column")
  expect(css).toContain("overflow-y: auto")
  expect(css).toContain("overflow-x: hidden")
  expect(css).toContain(".conversation-agent-rail__stack")
  expect(css).toContain(".conversation-agent-rail__tick-line")
  expect(css).toContain(".conversation-agent-rail-tooltip")
  expect(css).not.toContain("conversation-agent-rail__resize")
  expect(css).not.toContain('conversation-agent-rail__lanes[data-dragging="true"]')
  expect(css).not.toContain("cursor: grab")
  expect(css).not.toContain(".conversation-agent-rail .chat-avatar")
  expect(css).not.toContain("scrollbar-width: thin")
  const bodyIndex = html.indexOf('id="conversationBody"')
  const mountIndex = html.indexOf('id="solidConversationAgentRailMount"')
  const scrollShellIndex = html.indexOf('class="conversation-scroll-shell"')
  expect(bodyIndex).toBeGreaterThanOrEqual(0)
  expect(mountIndex).toBeGreaterThan(bodyIndex)
  expect(mountIndex).toBeLessThan(scrollShellIndex)
})

test("ConversationAgentRail keeps stack and row DOM stable across workflow refreshes", () => {
  const source = readFileSync(join(import.meta.dir, "../src/components/ConversationAgentRail.tsx"), "utf8")
  const css = readFileSync(join(import.meta.dir, "../src/styles/surfaces/conversation.css"), "utf8")
  expect(source).toContain("<Index each={stacks()}>")
  expect(source).toContain("<Index each={stack().records}>")
  expect(source).toContain("record: Accessor<AgentWorkflowRecord>")
  expect(source).toContain("data-stack-id={stack().id}")
  expect(source).toContain("data-count={stack().records.length}")
  expect(css).toContain(".conversation-agent-rail__stack")
  expect(css).toContain("grid-auto-rows: calc(12px * var(--ui-scale))")
})

test("ConversationAgentRail has no expanded detail surface", () => {
  const source = readFileSync(join(import.meta.dir, "../src/components/ConversationAgentRail.tsx"), "utf8")
  const css = readFileSync(join(import.meta.dir, "../src/styles/surfaces/conversation.css"), "utf8")
  expect(source).not.toContain("props.wide")
  expect(source).not.toContain("conversation-agent-rail__run")
  expect(source).not.toContain("conversation-agent-rail__report")
  expect(source).not.toContain("AgentReportDialog")
  expect(css).not.toContain("conversation-agent-rail__run")
  expect(css).not.toContain("conversation-agent-rail__report")
  expect(css).not.toContain("agent-report-dialog")
})

test("ConversationAgentRail hides the left rail when there are no workflow records", () => {
  const source = readFileSync(join(import.meta.dir, "../src/components/ConversationAgentRail.tsx"), "utf8")
  const css = readFileSync(join(import.meta.dir, "../src/styles/surfaces/conversation.css"), "utf8")
  expect(source).toContain("const hasRecords = createMemo(() => records().length > 0)")
  expect(source).toContain("<Show when={hasRecords()}>")
  expect(source).not.toContain("conversation-agent-rail__empty")
  expect(css).toContain(".conversation-agent-rail-host:empty")
  expect(css).toContain("display: none;")
})

test("ConversationAgentRail does not poll task trace for a removed expanded surface", () => {
  const source = readFileSync(join(import.meta.dir, "../src/components/ConversationAgentRail.tsx"), "utf8")
  expect(source).not.toContain("fetchTaskTrace")
  expect(source).not.toContain("invalidateTraceCache")
  expect(source).not.toContain("createResource")
  expect(source).not.toContain("traceEvents")
  expect(source).not.toContain("buildAgentWorkflow")
})

test("ConversationAgentRail does not use streamed card text as workflow summary input", () => {
  const workflow = readFileSync(join(import.meta.dir, "../src/utils/agent-workflow.ts"), "utf8")
  const rail = readFileSync(join(import.meta.dir, "../src/components/ConversationAgentRail.tsx"), "utf8")
  expect(workflow).not.toContain("textFromCard")
  expect(workflow).not.toContain("textFromPart")
  expect(workflow).not.toContain('source: "card_output"')
  expect(rail).not.toContain("cardMessageSegments")
  expect(rail).not.toContain("orderedMessageParts")
  expect(rail).not.toContain("No summary")
})
