import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"

const OVERLAY_ROOT = join(import.meta.dir, "..")

function readText(rel: string): string {
  return readFileSync(join(OVERLAY_ROOT, rel), "utf8")
}

describe("app/session dialog single source", () => {
  const appDialogService = readText("src/services/app-dialog.ts")
  const dialogService = readText("src/services/dialog.ts")
  const main = readText("src/main.tsx")
  const indexHtml = readText("src/index.html")
  const app = readText("src/components/App.tsx")
  const appHost = readText("src/components/AppDialogHost.tsx")
  const sessionHost = readText("src/components/SessionDialogHost.tsx")
  const goalHost = readText("src/components/GoalDialogHost.tsx")
  const configHost = readText("src/components/ConfigDialogHost.tsx")
  const dialogStore = readText("src/store/dialog.ts")
  const networkPanel = readText("src/components/settings/NetworkPanel.tsx")
  const llmService = readText("src/services/llm.ts")
  const appDialogBrowser = readText("test/browser/app-dialog-segmented-control.test.ts")

  test("app dialog service is store-backed, not bridge-backed DOM mutation", () => {
    expect(appDialogService).not.toContain("installAppDialogBridge")
    expect(appDialogService).not.toContain('document.getElementById("appDialogTitle")')
    expect(appDialogService).not.toContain('document.getElementById("appDialogBody")')
    expect(appDialogService).not.toContain("dialog.showModal()")
    expect(appDialogService).toContain('setDialogStore("app"')
    expect(appDialogService).toContain("settleAppDialog")
    expect(appDialogService).toContain("dismissAppDialog")
  })

  test("session dialog service no longer writes body/title through raw DOM", () => {
    expect(dialogService).not.toContain('document.getElementById("sessionDialogTitle")')
    expect(dialogService).not.toContain('document.getElementById("sessionDialogBody")')
    expect(dialogService).not.toContain('document.getElementById("sessionDialog")')
    expect(dialogService).not.toContain("dialog.showModal()")
    expect(dialogService).not.toContain("setupDialogBackdropClose")
    expect(dialogService).not.toContain('querySelectorAll("dialog.dialog")')
    expect(dialogService).toContain("closeBuildSessionDialog")
    expect(dialogService).toContain('setDialogStore("session"')
  })

  test("App owns host components instead of main binding close buttons", () => {
    expect(main).toContain('import { App } from "./components/App"')
    expect(main).toContain("render(() => <App />, host)")
    expect(main).toContain("ensureOverlayAppHost()")
    expect(app).toContain("<AppDialogHost />")
    expect(app).toContain("<SessionDialogHost />")
    expect(app).toContain("<GoalDialogHost />")
    expect(app).toContain("<ConfigDialogHost />")
    expect(main).not.toContain("render(() => <AppDialogHost")
    expect(main).not.toContain("render(() => <SessionDialogHost")
    expect(main).not.toContain("render(() => <GoalDialogHost")
    expect(main).not.toContain("render(() => <ConfigDialogHost")
    expect(main).not.toContain("btnCloseSession")
    expect(main).not.toContain("installAppDialogBridge")
    expect(main).not.toContain("installGoalFormHandlers")
    expect(main).not.toContain("setupDialogBackdropClose")
    expect(main).not.toContain('document.getElementById("configSidebar")?.addEventListener("click"')
  })

  test("App host is mounted before async init can block settings menus", () => {
    const ensureIndex = main.indexOf("ensureOverlayAppHost()")
    const initIndex = main.indexOf("await initApp({")
    expect(ensureIndex).toBeGreaterThanOrEqual(0)
    expect(initIndex).toBeGreaterThanOrEqual(0)
    expect(ensureIndex).toBeLessThan(initIndex)
    expect(app).toContain('id="configDialogHost"')
  })

  test("index html no longer contains static app/session/goal/config dialog shells", () => {
    expect(indexHtml).not.toContain('id="appDialog"')
    expect(indexHtml).not.toContain('id="btnAppDialogOk"')
    expect(indexHtml).not.toContain('id="sessionDialog"')
    expect(indexHtml).not.toContain('id="btnCloseSession"')
    expect(indexHtml).not.toContain('id="goalDialog"')
    expect(indexHtml).not.toContain('id="configDialog"')
    expect(indexHtml).not.toContain('id="btnCloseConfigDialog"')
  })

  test("host components own the canonical app/session/goal/config dialog ids", () => {
    expect(appHost).toContain('id="appDialog"')
    expect(appHost).toContain('id="btnAppDialogOk"')
    expect(appHost).toContain('id="appDialogBody"')
    expect(sessionHost).toContain('id="sessionDialog"')
    expect(sessionHost).toContain('id="btnCloseSession"')
    expect(sessionHost).toContain('id="sessionDialogBody"')
    expect(goalHost).toContain('id="goalDialog"')
    expect(goalHost).toContain('id="goalForm"')
    expect(goalHost).toContain('id="goalDescription"')
    expect(configHost).toContain('id="configDialog"')
    expect(configHost).toContain('id="configSidebar"')
    expect(configHost).toContain('id="btnCloseConfigDialog"')
  })

  test("session dialog host delegates title and form chrome to the Dialog primitive", () => {
    expect(sessionHost).toContain('title={dialogStore.session.title || t("log.title")}')
    expect(sessionHost).not.toContain('formClass="diff-dialog-form"')
    expect(sessionHost).not.toContain("diff-dialog-head")
    expect(sessionHost).not.toContain('class="dialog-title"')
    expect(sessionHost).not.toContain('id="sessionDialogTitle"')
    expect(sessionHost).not.toContain('titleAs="div"')
  })

  test("session dialog body states are written only by the service", () => {
    expect(sessionHost).toContain("innerHTML={dialogStore.session.bodyHtml}")
    expect(sessionHost).not.toContain("bodyHtml ||")
    expect(sessionHost).not.toContain("Loading...")

    expect(dialogService).toContain("bodyHtml: '<p class=\"empty-hint\">Loading…</p>'")
    expect(dialogService).toContain(
      'setDialogStore("session", "bodyHtml", \'<p class="empty-hint">No messages yet.</p>\')',
    )
    expect(dialogService).toContain(
      "const bodyHtml = html ? html : '<p class=\"empty-hint\">No displayable messages.</p>'",
    )
    expect(dialogService).toContain("Failed to load session:")
    expect(dialogService).not.toContain("bodyHtml ||")
    expect(dialogService).not.toContain("Loading...")
  })

  test("app dialog select input delegates listbox semantics to Kobalte", () => {
    expect(appHost).toContain('import { SelectControl } from "./ui/SelectControl"')
    expect(appHost).toContain("<SelectControl<AppDialogSelectOption>")
    expect(appHost).toContain('triggerID="appDialogSelect"')
    expect(appHost).toContain('triggerClass="field-input app-dialog-input app-dialog-select-trigger"')
    expect(appHost).toContain('ariaLabelledBy="appDialogSelectLabel"')
    expect(appHost).toContain('optionClass="app-dialog-select-option"')
    expect(appHost).toContain('"data-value": option.value')
    expect(appHost).not.toContain('import * as Select from "@kobalte/core/select"')
    expect(appHost).not.toContain("<Select.Root")
    expect(appHost).not.toContain("<Select.Trigger")
    expect(appHost).not.toContain("<Select.HiddenSelect")
    expect(appHost).not.toContain("function AppDialogSelectOptionItem")
    expect(appDialogService).toContain("dialogStore.app.selectValue")
    expect(appDialogService).not.toContain("dialogStore.app.selectValue || null")
    expect(appDialogService).toContain("validatedChoiceValue")
    expect(appDialogService).not.toContain("options.selectOptions?.[0]?.value")
    expect(appDialogService).not.toContain("dialogStore.app.selectValue || dialogStore.app.recommendedValue")
    expect(appHost).not.toContain("selectOptions()[0]")
    expect(llmService).not.toContain("prompt.options[0]")
    expect(llmService).not.toContain("methods[0]?.index")
    expect(appDialogService).not.toContain('document.getElementById("appDialogSelect")')
    expect(appDialogService).not.toContain("HTMLSelectElement")
    expect(appHost).not.toContain("<select")
    expect(appHost).not.toContain("<option")
    expect(appHost).not.toContain('class="field-input app-dialog-input custom-select app-dialog-select-trigger"')
  })

  test("config dialog mounts only the active settings tab body", () => {
    expect(configHost).toContain("<Show when={dialogStore.config.open}>")
    expect(configHost).toContain("renderActivePanel")
    expect(configHost).toContain("switch (tab)")
    expect(configHost).toContain("const activeConfigTab = createMemo(() => dialogStore.config.activeTab)")
    expect(configHost).toContain("const [renderedConfigTab, setRenderedConfigTab]")
    expect(configHost).toContain("window.requestAnimationFrame(() => setRenderedConfigTab(tab))")
    expect(configHost).toContain("data-config-panel={activeConfigTab()}")
    expect(configHost).not.toContain(
      "<PromptCatalog />\n            </div>\n          </div>\n          <div classList",
    )
    expect(configHost).not.toContain(
      "<ProvidersPanel />\n            </div>\n          </div>\n          <div classList",
    )
    expect(configHost).not.toContain("<AgentModelsPanel />\n            </div>\n          </div>")
  })

  test("config dialog switches requested tab before opening", () => {
    const openConfigDialog = dialogService.slice(dialogService.indexOf("export function openConfigDialog("))
    const focusIndex = openConfigDialog.indexOf("focusConfigSection(section)")
    const openIndex = openConfigDialog.indexOf('setDialogStore("config", "open", true)')
    const refreshIndex = openConfigDialog.indexOf("refreshSettingsInfoAfterDialogFrame()")
    expect(focusIndex).toBeGreaterThan(-1)
    expect(openIndex).toBeGreaterThan(-1)
    expect(refreshIndex).toBeGreaterThan(-1)
    expect(focusIndex).toBeLessThan(openIndex)
    expect(openIndex).toBeLessThan(refreshIndex)
    expect(dialogService).toContain("function refreshSettingsInfoAfterDialogFrame(): void")
    expect(dialogService).toContain("window.requestAnimationFrame(() =>")
    expect(dialogService).toContain("function focusConfigElementAfterDialogFrame(")
    expect(dialogService).toContain("configSectionFocusFrame = window.requestAnimationFrame(() =>")
    expect(dialogService).toContain("window.cancelAnimationFrame(configSectionFocusFrame)")
    expect(dialogService).toContain('focusConfigElementAfterDialogFrame("channelList"')
    expect(dialogService).toContain("focusConfigElementAfterDialogFrame(target.elementID")
    expect(dialogService).toContain("cancelConfigSectionFocusFrame()")
    expect(dialogService).not.toContain("queueMicrotask(() => {\n      const channelList")
    expect(dialogService).not.toContain("queueMicrotask(() => {\n      const element = document.getElementById(target.elementID!)")
  })

  test("network settings tab is a first-class config section and writes only scoped network.proxy", () => {
    expect(dialogStore).toContain('| "network"')
    expect(dialogStore).toContain('{ id: "network", labelKey: "network.title" }')
    expect(configHost).toContain('network: "config-network"')
    expect(configHost).toContain('case "network":')
    expect(configHost).toContain("<NetworkPanel />")
    expect(networkPanel).toContain("patchConfig({ network: { proxy: nextProxy } }, currentProjectConfigRequestOptions())")
    expect(networkPanel).toContain("patchConfig({ network: { proxy: null } }, currentProjectConfigRequestOptions())")
    expect(networkPanel).toContain("testNetworkProxy(proxyDraft(input))")
    expect(networkPanel).toContain('t("network.proxy.delete_button_title")')
    expect(networkPanel).toContain('t("network.proxy.deleted")')
    expect(networkPanel).toContain('t("network.proxy.test_button")')
    expect(networkPanel).toContain('class="provider-test-result"')
    expect(networkPanel).toContain("llmProvider: llmProvider()")
    expect(networkPanel).toContain("webResearch: webResearch()")
    expect(networkPanel).toContain("username: input.proxyUsername")
    expect(networkPanel).toContain("password: input.proxyPassword")
    expect(networkPanel).not.toContain('apiJson("config")')
    expect(networkPanel).not.toContain("updateConfig(")
  })

  test("task route and queue decisions use card choices instead of select UI", () => {
    expect(appHost).toContain('dialogStore.app.kind === "task-queue-decision"')
    expect(appHost).toContain("import { SegmentedControl")
    expect(appHost).toContain("<SegmentedControl")
    expect(appHost).toContain('itemClass="app-dialog-decision__choice"')
    expect(appHost).toContain("onActivate={chooseTaskDecision}")
    expect(appHost).toContain("choice.dataset.value === dialogStore.app.selectValue")
    expect(appHost).toContain("focusTarget?.focus()")
    expect(appHost).toContain("isTaskCardDecision()")
    expect(appHost).toContain("chooseTaskDecision")
    expect(appHost).toContain("settleAppDialog(true, dialogStore.app.epoch, value)")
    expect(appHost).toContain("isTaskCardDecision() ? undefined")
    expect(appHost).toContain("hidden: dialogStore.app.select !== true || isTaskCardDecision()")
    expect(appHost).toContain("hasTaskDecisionCountdown()")
    expect(appHost).toContain('t("task.queue_decision.countdown"')
    expect(appHost).not.toContain('role="group"')
    expect(appHost).not.toContain("<button")
    expect(appHost).not.toContain("data-selected")
    expect(appHost).not.toContain("!isTaskRouteDecision()) return")
    expect(appDialogBrowser).toContain("await page.goto(`${server.origin}/ui/index.html`")
    expect(appDialogBrowser).toContain('await page.click("#chatSend")')
    expect(appDialogBrowser).toContain('await page.keyboard.press("Enter")')
    expect(appDialogBrowser).toContain('await page.keyboard.press("Space")')
    expect(appDialogBrowser).not.toContain("page.setContent")
  })
})
