import { expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import path from "node:path"
import { closeFileEditor, fileWorkbenchOpen, openFileEditor, selectedFilePath } from "../src/services/file-workbench"

const ROOT = path.resolve(import.meta.dir, "..")

function readText(rel: string): string {
  return readFileSync(path.join(ROOT, rel), "utf8")
}

test("file explorer, diff, and editor are wired through center workbench panels", () => {
  const explorer = readText("src/components/FileExplorerPanel.tsx")
  const editor = readText("src/components/FileEditorPane.tsx")
  const filesPanel = readText("src/components/FileChangesPanel.tsx")
  const codeEditor = readText("src/components/primitives/CodeEditor.tsx")
  const service = readText("src/services/file-workbench.ts")
  const html = readText("src/index.html")
  const main = readText("src/main.tsx")
  const inspectorCss = readText("src/styles/surfaces/inspector.css")
  const activityCss = readText("src/styles/surfaces/activity.css")
  const workspaceCss = readText("src/styles/surfaces/workspace.css")

  expect(html).toContain('id="solidLeftActivityToolbar"')
  expect(html).not.toContain('id="leftPanelExplorer"')
  expect(html).not.toContain('id="leftPanelChanges"')
  expect(html).not.toContain('data-left-activity="tasks"')
  expect(html).toContain('id="centerWorkbench"')
  expect(html).toContain('id="centerWorkbenchWorkflow"')
  expect(html).toContain('id="centerWorkbenchExplorer"')
  expect(html).toContain('id="centerWorkbenchDiff"')
  expect(html).toContain('id="centerWorkbenchFile"')
  expect(html).toContain('id="solidFileExplorerMount"')
  expect(html).toContain('id="solidFileChangesMount"')
  expect(html).toContain('id="chatContentFrame"')
  expect(html).not.toContain('id="chatFileEditorPane"')
  expect(html).not.toContain('data-chat-view="file" data-active="false"')
  expect(html).not.toContain('id="chatDiffPane"')
  expect(html).not.toContain('data-chat-view="diff" data-active="false"')
  expect(html).toContain('id="solidFileEditorMount"')
  expect(html).toContain('class="center-workbench-activity chat-file-editor-activity file-editor-mount"')
  expect(html).not.toContain('id="workspaceResizer"')
  expect(html).not.toContain('id="rightPanelExplorer"')
  expect(html).not.toContain('id="rightPanelFiles"')
  expect(html).not.toContain('id="solidRightFilesMount"')
  expect(html).not.toContain('id="solidFileEditorToggleMount"')
  expect(html).not.toContain('id="solidFileEditorMount" class="sections-files-tab"')
  expect(main).toContain(
    '<FileExplorerPanel active={() => isCenterWorkbenchPanelOpen("explorer")} directory={activeDirectory}',
  )
  expect(main).toContain("<FileEditorPane")
  expect(main).toContain("<FileChangesPanel")
  expect(main).toContain('workflow: document.getElementById("centerWorkbenchWorkflow")')
  expect(main).toContain("diffOpen={workspaceOpen()}")
  expect(main).toContain('openCenterWorkbenchPanel("diff")')
  expect(main).not.toContain('setLeftActivity("changes")')
  expect(main).not.toContain('document.getElementById("leftPanelChanges")')
  expect(main).toContain('document.getElementById("solidFileChangesMount")')
  expect(main).not.toContain('changes: document.getElementById("leftPanelChanges")')
  expect(main).toContain('file: document.getElementById("centerWorkbenchFile")')
  expect(main).toContain('diff: document.getElementById("centerWorkbenchDiff")')
  expect(main).not.toContain('setChatView("file")')
  expect(main).not.toContain('setChatView("diff")')
  expect(main).toContain("closeFileEditor()")
  expect(main).toContain("fileEditorMountEl")
  expect(main).not.toContain("hidden = !fileWorkbenchOpen()")
  expect(main).not.toContain('document.getElementById("workspaceResizer")')
  expect(main).not.toContain('if (fileWorkbenchOpen() || workspaceOpen()) setRightPanelTab("files")')
  expect(main).not.toContain('document.getElementById("solidFileEditorToggleMount")')
  expect(main).not.toContain("FileEditorToggle")
  expect(main).not.toContain("frame.dataset.editorOpen = fileWorkbenchOpen() || workspaceOpen()")
  expect(main).not.toContain("frame.dataset.editorOpen = activeTaskID() || selectedFilePath() || workspaceOpen()")

  expect(explorer).toContain("apiJson(`file?path=")
  expect(explorer).toContain("apiJson(`find/file?")
  expect(explorer).toContain("INITIAL_DIRECTORY_LOAD_DELAY_MS")
  expect(explorer).toContain("ACTIVE_DIRECTORY_REFRESH_INTERVAL_MS")
  expect(explorer).toContain("props.active?.() ?? true")
  expect(explorer).toContain('props.directory ? props.directory().trim() : "unscoped"')
  expect(explorer).toContain("setChildrenByPath(new Map())")
  expect(explorer).toContain("!active() || !currentDirectory")
  expect(explorer).toContain('window.setTimeout(() => void loadDirectory("")')
  expect(explorer).toContain("window.setInterval")
  expect(explorer).toContain("loadDirectory(path, { force: true })")
  expect(explorer).toContain("createDeferred")
  expect(explorer).toContain("childrenByPath")
  expect(explorer).toContain("expandedPaths")
  expect(explorer).toContain("directoryErrors")
  expect(explorer).toContain("rootLoading")
  expect(explorer).toContain("searchLoading")
  expect(explorer).toContain('t("explorer.load_failed")')
  expect(explorer).not.toContain("next.set(path, [])")
  expect(explorer).toContain('from "virtua/solid"')
  expect(explorer).toContain("VIRTUAL_EXPLORER_ROW_THRESHOLD")
  expect(explorer).toContain('<span class="file-explorer-chevron" />')
  expect(explorer).toContain("openFileEditor")

  expect(editor).toContain("apiJson(`file/content?path=")
  expect(editor).toContain('method: "PATCH"')
  expect(editor).toContain("body: JSON.stringify({ path, content })")
  expect(editor).toContain('import { CodeEditor } from "./primitives/CodeEditor"')
  expect(editor).toContain("<CodeEditor")
  expect(editor).not.toContain("<textarea")
  expect(editor).toContain("dirty")
  expect(codeEditor).toContain('import { basicSetup, EditorView } from "codemirror"')
  expect(codeEditor).toContain("EditorView.updateListener")
  expect(codeEditor).toContain("update.state.doc.toString()")
  expect(codeEditor).toContain("view?.destroy()")
  expect(service).not.toContain('createSignal<"messages" | "editor">')
  expect(service).not.toContain("toggleFileEditorFocus")
  expect(service).not.toContain("showWorkbenchPane")
  expect(service).toContain("const [fileWorkbenchOpen, setFileWorkbenchOpen]")
  expect(service).toContain("setFileWorkbenchOpen(false)")
  expect(editor).not.toContain("showMessagesPane")
  expect(filesPanel).toContain("<ChangesPanel hasSelectedTask />")
  expect(filesPanel).toContain("<DiffPreviewPanel")
  expect(filesPanel).not.toContain("<FileEditorPane")
  expect(filesPanel).toContain("data-active-view={activeView()}")
  expect(filesPanel).toContain("<Tabs")
  expect(filesPanel).toContain("<Tab")
  expect(filesPanel).toContain('value="diff"')
  expect(filesPanel).toContain("props.onActiveViewChange")
  expect(main).toContain("fileChangesActiveView")
  expect(main).toContain("activeView={fileChangesActiveView()}")
  expect(main).toContain("onActiveViewChange={setFileChangesActiveView}")

  expect(inspectorCss).toContain(".file-explorer-panel")
  expect(inspectorCss).toContain('.file-explorer-list[data-virtualized="true"]')
  expect(inspectorCss).toContain(".file-explorer-retry")
  expect(activityCss).toContain(".sidebar-file-changes-panel")
  expect(activityCss).toContain("container: side-activity / inline-size")
  expect(activityCss).toContain(".file-changes-panel")
  expect(activityCss).toContain(".file-changes-diff-header")
  expect(inspectorCss).not.toContain(".right-files-panel")
  expect(inspectorCss).not.toContain(".right-files-diff-header")
  expect(workspaceCss).toContain(".chat-content-frame")
  expect(workspaceCss).toContain("container: chat-workbench / inline-size")
  expect(workspaceCss).toContain(".center-workbench")
  expect(workspaceCss).not.toContain(".center-workbench-tabs")
  expect(workspaceCss).toContain('.center-workbench-view[data-open="true"]')
  expect(workspaceCss).toContain(".center-workbench-resizer")
  expect(workspaceCss).toContain(".chat-file-editor-activity")
  expect(workspaceCss).not.toContain(".chat-diff-activity.workspace-mount")
  expect(workspaceCss).toContain(".file-editor-mount")
  expect(workspaceCss).not.toContain(".file-editor-mount[hidden]")
  expect(workspaceCss).not.toContain(".workspace-mount[hidden]")
  expect(workspaceCss).not.toContain(".pane-resizer.pane-resizer-workspace")
  expect(workspaceCss).not.toContain(".file-editor-toggle")
  expect(workspaceCss).not.toContain(".message-workbench")
  expect(workspaceCss).not.toContain("@container message-workbench (max-width: 720px)")
  expect(workspaceCss).toContain(".file-editor-code")
  expect(workspaceCss).toContain(".file-editor-code .cm-editor")
  expect(workspaceCss).not.toContain("@container chat-workbench (max-width: 860px)")
  expect(workspaceCss).not.toContain('[data-editor-focus="editor"] .chat-message-pane')
  expect(workspaceCss).not.toContain('[data-editor-focus="messages"] .file-editor-mount')
})

test("file workbench open state is independent from selected task presence", () => {
  closeFileEditor()
  expect(fileWorkbenchOpen()).toBe(false)
  expect(selectedFilePath()).toBe("")

  openFileEditor("src/main.tsx")
  expect(fileWorkbenchOpen()).toBe(true)
  expect(selectedFilePath()).toBe("src/main.tsx")

  closeFileEditor()
  expect(fileWorkbenchOpen()).toBe(false)
  expect(selectedFilePath()).toBe("")
})
