import { expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import path from "node:path"

const ROOT = path.resolve(import.meta.dir, "..")

function readText(rel: string): string {
  return readFileSync(path.join(ROOT, rel), "utf8")
}

test("file explorer and editor are wired as a VS Code-style split workbench", () => {
  const explorer = readText("src/components/FileExplorerPanel.tsx")
  const editor = readText("src/components/FileEditorPane.tsx")
  const workbench = readText("src/components/MessageWorkbenchPane.tsx")
  const codeEditor = readText("src/components/primitives/CodeEditor.tsx")
  const toggle = readText("src/components/FileEditorToggle.tsx")
  const service = readText("src/services/file-workbench.ts")
  const tabs = readText("src/components/RightPanelTabs.tsx")
  const html = readText("src/index.html")
  const main = readText("src/main.tsx")
  const inspectorCss = readText("src/styles/surfaces/inspector.css")
  const workspaceCss = readText("src/styles/surfaces/workspace.css")

  expect(tabs).toContain('export type RightPanelTab = "explorer" | "inspector"')
  expect(tabs).toContain('export const DEFAULT_RIGHT_PANEL_TAB: RightPanelTab = "explorer"')
  expect(tabs).not.toContain('props.onSelect("changes")')
  expect(html).toContain('id="rightPanelExplorer"')
  expect(html).toContain('id="solidFileExplorerMount"')
  expect(html).toContain('id="chatContentFrame"')
  expect(html).toContain('id="solidFileEditorMount"')
  expect(html).toContain('id="solidFileEditorToggleMount"')
  expect(main).toContain('<FileExplorerPanel active={() => rightPanelTab() === "explorer"} directory={activeDirectory}')
  expect(main).toContain("<MessageWorkbenchPane")
  expect(main).toContain("diffOpen={workspaceOpen()}")
  expect(main).toContain("frame.dataset.editorOpen = activeTaskID() || selectedFilePath() || workspaceOpen()")

  expect(explorer).toContain('apiJson(`file?path=')
  expect(explorer).toContain('apiJson(`find/file?')
  expect(explorer).toContain("INITIAL_DIRECTORY_LOAD_DELAY_MS")
  expect(explorer).toContain("ACTIVE_DIRECTORY_REFRESH_INTERVAL_MS")
  expect(explorer).toContain('props.active?.() ?? true')
  expect(explorer).toContain('props.directory ? props.directory().trim() : "unscoped"')
  expect(explorer).toContain("setChildrenByPath(new Map())")
  expect(explorer).toContain("!active() || !currentDirectory")
  expect(explorer).toContain('window.setTimeout(() => void loadDirectory("")')
  expect(explorer).toContain("window.setInterval")
  expect(explorer).toContain("loadDirectory(path, { force: true })")
  expect(explorer).toContain("createDeferred")
  expect(explorer).toContain("childrenByPath")
  expect(explorer).toContain("expandedPaths")
  expect(explorer).toContain("directoryErrors")
  expect(explorer).toContain("rootLoading")
  expect(explorer).toContain("searchLoading")
  expect(explorer).toContain('t("explorer.load_failed")')
  expect(explorer).not.toContain("next.set(path, [])")
  expect(explorer).toContain('from "virtua/solid"')
  expect(explorer).toContain("VIRTUAL_EXPLORER_ROW_THRESHOLD")
  expect(explorer).toContain('<span class="file-explorer-chevron" />')
  expect(explorer).toContain("openFileEditor")

  expect(editor).toContain('apiJson(`file/content?path=')
  expect(editor).toContain('method: "PATCH"')
  expect(editor).toContain('body: JSON.stringify({ path, content })')
  expect(editor).toContain('import { CodeEditor } from "./primitives/CodeEditor"')
  expect(editor).toContain("<CodeEditor")
  expect(editor).not.toContain("<textarea")
  expect(editor).toContain("dirty")
  expect(codeEditor).toContain('import { basicSetup, EditorView } from "codemirror"')
  expect(codeEditor).toContain("EditorView.updateListener")
  expect(codeEditor).toContain("update.state.doc.toString()")
  expect(codeEditor).toContain("view?.destroy()")
  expect(toggle).toContain("toggleFileEditorFocus")
  expect(toggle).toContain("activeTaskID")
  expect(service).toContain('createSignal<"messages" | "editor">')
  expect(service).not.toContain("if (!selectedFilePath()) return")
  expect(workbench).toContain("<ChangesPanel hasSelectedTask />")
  expect(workbench).toContain("<FileEditorPane />")
  expect(workbench).toContain("<DiffPreviewPanel")
  expect(workbench).toContain('data-active-view={activeView()}')
  expect(workbench).toContain('setActiveView("detail")')

  expect(inspectorCss).toContain(".file-explorer-panel")
  expect(inspectorCss).toContain(".file-explorer-list[data-virtualized=\"true\"]")
  expect(inspectorCss).toContain(".file-explorer-retry")
  expect(workspaceCss).toContain(".chat-content-frame")
  expect(workspaceCss).toContain("container: chat-workbench / inline-size")
  expect(workspaceCss).toContain(".file-editor-mount")
  expect(workspaceCss).toContain("container: message-workbench / inline-size")
  expect(workspaceCss).toContain(".message-workbench")
  expect(workspaceCss).toContain(".message-workbench-changes")
  expect(workspaceCss).toContain(".message-workbench-detail")
  expect(workspaceCss).toContain("@container message-workbench (max-width: 720px)")
  expect(workspaceCss).toContain(".file-editor-code")
  expect(workspaceCss).toContain(".file-editor-code .cm-editor")
  expect(workspaceCss).toContain('@media (max-width: 1280px)')
  expect(workspaceCss).toContain("@container chat-workbench (max-width: 860px)")
  expect(workspaceCss).toContain('[data-editor-focus="editor"] .chat-message-pane')
  expect(workspaceCss).toContain('[data-editor-focus="messages"] .file-editor-mount')
})
