import { expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"
import { defaultPanelRemainingMinWidth, PANEL_PANE_CONFIG, type PaneConfig } from "../src/services/pane"

function readSrc(rel: string): string {
  return readFileSync(join(import.meta.dir, "..", "src", rel), "utf8")
}

test("PANEL_PANE_CONFIG targets the default panel's elements and variables", () => {
  expect(PANEL_PANE_CONFIG).toEqual({
    bodyId: "panelBody",
    leftHandleId: "leftPaneResizer",
    leftFixedControlIds: ["solidLeftActivityToolbar"],
    leftControls: ["sidebar", "workspaceMain"],
    remainingFixedControlIds: ["solidRightActivityToolbar"],
    remainingMinWidth: defaultPanelRemainingMinWidth,
    sidebarVar: "--ui-sidebar-width",
  } satisfies PaneConfig)
})

test("default pane resizer exposes separator semantics through the pane service", () => {
  const html = readSrc("index.html")
  const main = readSrc("main.tsx")
  const pane = readSrc("services/pane.ts")
  const css = readSrc("styles/surfaces/workspace.css")
  expect(html).toContain('id="leftPaneResizer"')
  expect(html).toContain('aria-label="Resize left panel"')
  expect(html).toContain('aria-controls="sidebar workspaceMain"')
  expect(html).toContain('aria-valuenow="0"')
  expect(html).toContain('tabindex="0"')
  expect(pane).toContain("function renderPaneHandleSemantics")
  expect(pane).toContain("const renderPaneHandleSemanticsOnFrame = createAnimationFrameScheduler(flushPaneHandleSemantics)")
  expect(pane).toContain("function schedulePaneHandleSemantics")
  expect(pane).toContain("function resizePaneByKeyboard")
  expect(pane).toContain('import { createAnimationFrameScheduler, type AnimationFrameScheduler } from "../utils/animation-frame"')
  expect(pane).toContain('import { layoutTokenPx } from "../utils/layout-tokens"')
  expect(pane).toContain('layoutTokenPx("--ui-rail-width")')
  expect(pane).toContain('layoutTokenPx("--ui-rail-min-width")')
  expect(pane).toContain('layoutTokenPx("--ui-chat-min-width")')
  expect(pane).toContain('leftFixedControlIds: ["solidLeftActivityToolbar"]')
  expect(pane).toContain('remainingFixedControlIds: ["solidRightActivityToolbar"]')
  expect(pane).toContain("remainingMinWidth: defaultPanelRemainingMinWidth")
  expect(pane).toContain("const leftFixed = renderedControlWidthSum(config.leftFixedControlIds)")
  expect(pane).toContain("const remainingFixed = renderedControlWidthSum(config.remainingFixedControlIds)")
  expect(pane).toContain("const total = panelWidth - leftHandle - leftFixed")
  expect(pane).toContain("const railMax = Math.max(railMin, total - remainingFixed - remainingContentMin)")
  expect(pane).not.toContain("120 * scale")
  expect(pane).not.toContain("300 * scale")
  expect(pane).toContain("function flushPendingPaneResize")
  expect(pane).toContain("pendingClientX")
  expect(pane).toContain("paneDrag.resizeOnFrame.schedule()")
  expect(pane).toContain("paneDrag.resizeOnFrame.cancel()")
  expect(pane).not.toContain("resizePane(paneDrag.side, event.clientX")
  expect(pane).not.toContain('side: "left" | "right"')
  expect(pane).not.toContain("sectionsWidth")
  expect(pane).not.toContain("rightPanelCollapsed")
  expect(pane).toContain("aria-valuemin")
  expect(pane).toContain("aria-valuemax")
  expect(pane).toContain("aria-valuenow")
  expect(pane).toContain("tabIndex = enabled ? 0 : -1")
  expect(pane).toContain('addEventListener("keydown"')
  expect(css).toContain(".pane-resizer:focus-visible")
  expect(css).toContain("outline: var(--oc-border-width) solid var(--accent)")
  expect(css).not.toContain('body[data-resizing="row"]')
  expect(css).not.toContain("row-resize")
  expect(css).not.toContain('body[data-resizing="true"] .pane-resizer::before')
  expect(css).toContain('body[data-resizing="true"] .pane-resizer::after')
  expect(pane).toContain('document.body.dataset.resizing = "true"')
  expect(pane).not.toContain('document.body.dataset.resizing = "row"')
  expect(main).not.toContain("leftResizer.dataset.disabled")
})

test("pane layout writes and handle semantics run in separate frame phases", () => {
  const pane = readSrc("services/pane.ts")
  const main = readSrc("main.tsx")
  const renderPaneLayoutStart = pane.indexOf("export function renderPaneLayout")
  const applyWindowResizeStart = main.indexOf("function applyWindowResize(): void")
  const applyWindowResizeEnd = main.indexOf("const applyWindowResizeOnFrame", applyWindowResizeStart)

  expect(renderPaneLayoutStart).toBeGreaterThan(0)
  expect(applyWindowResizeStart).toBeGreaterThan(0)
  expect(applyWindowResizeEnd).toBeGreaterThan(applyWindowResizeStart)

  const renderPaneLayoutFunction = pane.slice(renderPaneLayoutStart, pane.indexOf("\n}\n", renderPaneLayoutStart) + 3)
  const applyWindowResizeFunction = main.slice(applyWindowResizeStart, applyWindowResizeEnd)

  expect(pane).toContain("const pendingPaneHandleSemantics = new Map<PaneConfig, PaneState>()")
  expect(pane).toContain("pendingPaneHandleSemantics.set(config, { ...state })")
  expect(pane).toContain("renderPaneHandleSemanticsOnFrame.schedule()")
  expect(renderPaneLayoutFunction).toContain("setPaneWidthProperty(config.sidebarVar, widths.sidebar)")
  expect(renderPaneLayoutFunction).not.toContain("setPaneWidthProperty(config.sectionsVar")
  expect(renderPaneLayoutFunction).toContain("schedulePaneHandleSemantics(state, config)")
  expect(renderPaneLayoutFunction).not.toContain("renderPaneHandleSemantics(state, config)")
  expect(main).toContain("const renderPaneLayoutOnFrame = createAnimationFrameScheduler(flushPaneLayout)")
  expect(main).toContain("function schedulePaneLayout(state: PaneState): void")
  expect(applyWindowResizeFunction).toContain("applyZoom(settingsStore.zoom)")
  expect(applyWindowResizeFunction).toContain("schedulePaneLayout(paneCallbacks.getState())")
  expect(applyWindowResizeFunction).not.toContain("renderPaneLayout(paneCallbacks.getState(), PANEL_PANE_CONFIG)")
})

test("Mission no longer owns an independent pane layout or persisted widths", () => {
  const pane = readSrc("services/pane.ts")
  const mission = readSrc("components/Mission.tsx")
  const settings = readSrc("store/settings.ts")
  expect(pane).not.toContain("MISSION_PANE_CONFIG")
  expect(pane).not.toContain("missionLedgerResizer")
  expect(pane).not.toContain("missionChannelsResizer")
  expect(mission).not.toContain("initPaneResizers")
  expect(mission).not.toContain("renderPaneLayout")
  expect(mission).not.toContain("missionLedgerWidth")
  expect(mission).not.toContain("missionChannelsWidth")
  expect(settings).not.toContain("missionLedgerWidth")
  expect(settings).not.toContain("missionChannelsWidth")
})

test("default pane layout has no retired right pane width source", () => {
  const pane = readSrc("services/pane.ts")
  expect(pane).toContain("const panelBody = document.getElementById(config.bodyId)")
  expect(pane).toContain("function paneResizeBounds")
  expect(pane).toContain("clientX - bounds.bodyRect.left")
  expect(pane).not.toContain("bounds.bodyRect.right - clientX")
  expect(pane).not.toContain("export function defaultSectionsWidth")
  expect(pane).not.toContain("state.sectionsWidth")
  expect(pane).not.toContain("document.getElementById(config.centerId)")
  expect(pane).toContain("renderedControlWidthSum(config.leftFixedControlIds)")
  expect(pane).toContain("renderedControlWidthSum(config.remainingFixedControlIds)")
})

test("settings no longer persist retired right pane state", () => {
  const settings = readSrc("store/settings.ts")
  const storage = readSrc("services/overlay-settings-storage.ts")
  expect(settings).toContain('typeof input?.sidebarCollapsed === "boolean"')
  expect(settings).not.toContain("rightPanelCollapsed")
  expect(settings).not.toContain("sectionsWidth")
  expect(storage).toContain('sidebarCollapsed: read("oc_sidebar_collapsed") === "true"')
  expect(storage).not.toContain("oc_right_panel_collapsed")
  expect(storage).not.toContain("oc_sections_width")
})

test("center workbench no longer keeps an outer width source", () => {
  const settings = readSrc("store/settings.ts")
  const storage = readSrc("services/overlay-settings-storage.ts")
  const main = readSrc("main.tsx")
  expect(settings).not.toContain("centerWorkbenchWidth")
  expect(storage).not.toContain("oc_center_workbench_width")
  expect(main).not.toContain("centerWorkbenchWidth")
  expect(main).not.toContain("centerWorkbenchResizer")
})

test("center workbench panel weights persist through the existing settings source", () => {
  const settings = readSrc("store/settings.ts")
  const storage = readSrc("services/overlay-settings-storage.ts")
  const main = readSrc("main.tsx")
  const html = readSrc("index.html")
  const css = readSrc("styles/surfaces/workspace.css")
  expect(settings).toContain("centerWorkbenchPanelWeights: Record<string, number> | null")
  expect(settings).toContain("centerWorkbenchPanelWeights: sanitizePanelWeights(input?.centerWorkbenchPanelWeights)")
  expect(settings).toContain("centerWorkbenchPanelWeights: input.centerWorkbenchPanelWeights || undefined")
  expect(storage).toContain('centerWorkbenchPanelWeights: readJSON("oc_center_workbench_panel_weights")')
  expect(storage).toContain('writeOptionalJSON("oc_center_workbench_panel_weights", input.centerWorkbenchPanelWeights)')
  expect(main).toContain('setSettingsStore("centerWorkbenchPanelWeights"')
  expect(main).toContain("renderCenterWorkbenchPanelWeights")
  expect(main).toContain("renderCenterWorkbenchPanelSeparators")
  expect(main).toContain("resizeCenterWorkbenchPanelByKeyboard")
  expect(main).not.toContain("centerWorkbenchShowsAdjacentPanels")
  expect(main).toContain("centerWorkbenchResizeRange(totalWidth, minWidth)")
  expect(main).toContain("const enabled = !!rightPanel && !!metrics")
  expect(main).not.toContain('window.matchMedia("(max-width: 520px)")')
  expect(main).toContain("clampCenterWorkbenchResizeWidth(metrics.totalWidth, metrics.minWidth, rawLeftWidth)")
  expect(main).toContain("separator.addEventListener(")
  expect(main).toContain('"[data-center-workbench-separator]"')
  expect(main).toContain('"aria-controls"')
  expect(main).not.toContain("findCenterWorkbenchResizePanel")
  expect(main).not.toContain("boundaryX")
  expect(main).not.toContain("data.resizableNext")
  expect(main).not.toContain("data.resizablePrev")
  expect(html).toContain('data-center-workbench-separator="workflow"')
  expect(html).toContain('data-center-workbench-separator="notifications"')
  expect(css).toContain("--center-workbench-panel-grow")
  expect(css).toContain(".center-workbench-panel-separator")
  expect(css).toContain(".center-workbench-panel-separator:focus-visible")
  expect(css).toContain("outline: var(--oc-border-width) solid var(--accent)")
  expect(css).toContain("outline-offset: calc(1px * var(--ui-scale))")
  expect(css).not.toContain("--oc-focus-ring-width")
  expect(css).not.toContain("var(--focus)")
  expect(css).not.toContain(".center-workbench-resizer")
  expect(css).not.toContain('.center-workbench-view[data-resizable-next="true"]::after')
  expect(css).toContain('body[data-center-workbench-panel-resizing="true"]')
})

test("the default Panel still passes PANEL_PANE_CONFIG", () => {
  const main = readSrc("main.tsx")
  expect(main).toContain("PANEL_PANE_CONFIG")
  expect(main).toContain("initPaneResizers(paneCallbacks, PANEL_PANE_CONFIG)")
})
