import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"

const OVERLAY_ROOT = join(import.meta.dir, "..")

function read(path: string): string {
  return readFileSync(join(OVERLAY_ROOT, path), "utf8")
}

describe("overlay project directory request loop", () => {
  test("API configuration waits for settings hydration before reading active directory", () => {
    const source = read("src/main.tsx")
    expect(source).toMatch(/createEffect\(\(\) => \{\s*if \(!settingsHydrated\(\)\) return\s*configureApi\(\{/)
  })

  test("skill market auto-load is keyed by active directory, not empty catalogue state", () => {
    const source = read("src/components/settings/SkillMarketPanel.tsx")
    expect(source).toContain('const [loadedMarketDirectory, setLoadedMarketDirectory] = createSignal("")')
    expect(source).toContain("const directory = currentDirectory()")
    expect(source).toContain('props.mode !== "skill-market" || props.active !== true')
    expect(source).toContain("if (loadedMarketDirectory() === directory) return")
    expect(source).toContain("loadSkillMarket()")
    expect(source).toContain(".then(() => setLoadedMarketDirectory(directory))")
    expect(source).not.toContain("market().length === 0")
  })

  test("MCP panel refreshes while active so external backend connection changes surface", () => {
    const source = read("src/components/settings/SkillMarketPanel.tsx")
    expect(source).toContain("createVisibilityInterval")
    expect(source).toContain("MCP_STATUS_REFRESH_INTERVAL_MS")
    expect(source).toContain("function requireActiveDirectory()")
    expect(source).toContain('props.mode !== "mcp" || props.active !== true')
    expect(source).toContain("function currentDirectory()")
    expect(source).toContain("configureApi({ directory })")
    expect(source).toContain("const directory = currentDirectory()")
    expect(source).toContain("if (props.active !== true) return")
    expect(source).toContain('setPanelNotice(t("workspace.no_directory"), "warn")')
    const mcpPanelStart = source.indexOf("export function McpPanel")
    const mcpPanelEnd = source.indexOf("export function SkillMarketPanel", mcpPanelStart)
    const mcpPanelBlock = source.slice(mcpPanelStart, mcpPanelEnd)
    expect(mcpPanelBlock).toContain('mode="mcp"')
    expect(mcpPanelBlock).toContain("active={props.active ?? true}")
    expect(source).toContain("refreshMcpStatus().catch")
    expect(source).toContain("const mcp = createMemo((): Record<string, McpItem> => ({ ...(appStore.mcp")
    expect(source).not.toContain("panelMcp")
    expect(source).not.toContain("setPanelMcp")
    expect(source).toContain("if (!props.compact) return")
    expect(source).toContain('if (props.mode === "mcp")')
    expect(source).toContain("mcpConnectionStatusOrDisabledLabel")
    expect(source).toContain("mcpConnectionStatusOrDisabledTone")
    expect(source).not.toContain("function mcpStatusLabel")
    expect(source).not.toContain("function mcpStatusTone")
    expect(source).not.toContain("function handleConnectMcp")
    expect(source).not.toContain('t("mcp.connect_action")')
    expect(source).toContain("interval.dispose()")
    expect(source).not.toContain("hasConnectingMcp")
  })

  test("installed skill panel refresh is scoped away from MCP status", () => {
    const source = read("src/components/settings/SkillMarketPanel.tsx")
    const main = read("src/main.tsx")
    expect(source).toContain('props.mode !== "skill" || props.active !== true')
    expect(source).toContain("if (props.active !== true) return")
    expect(source).toContain("const directory = currentDirectory()")
    expect(source).toContain('setPanelNotice(t("workspace.no_directory"), "warn")')
    expect(source).toContain("refreshSkillMounts().catch")
    expect(source).toContain("const skills = createMemo((): SkillItem[] => [...(appStore.skills")
    expect(source).not.toContain("panelSkills")
    expect(source).not.toContain("setPanelSkills")
    expect(source).toContain('if (props.mode === "skill")')
    expect(source).toContain('if (props.mode === "skill-market")')
    expect(source).toContain('mode="skill"')
    expect(source).toContain("active={props.active ?? true}")
    expect(main).toContain(
      '<SkillsPanel active={selectedLeftPanelActivity() === "skill"} directory={activeDirectory} compact />',
    )
    expect(main).toContain(
      '<McpPanel active={selectedLeftPanelActivity() === "mcp"} directory={activeDirectory} compact />',
    )
    expect(main).not.toContain('<SkillsPanel active={selectedLeftPanelActivity() === "skill"} compact />')
    expect(main).not.toContain('<McpPanel active={selectedLeftPanelActivity() === "mcp"} compact />')
    expect(main).toContain('active={selectedLeftPanelActivity() === "memory"}')
    expect(main).toContain("directory={activeDirectory}")
  })

  test("settings skill and MCP panels receive the active project directory explicitly", () => {
    const source = read("src/components/ConfigDialogHost.tsx")
    expect(source).toContain('import { activeProjectDirectory } from "../services/project-directory"')
    expect(source).toContain("<SkillsPanel directory={activeProjectDirectory} />")
    expect(source).toContain('<SkillMarketPanel active={true} directory={activeProjectDirectory} />')
    expect(source).toContain("<McpPanel directory={activeProjectDirectory} />")
    expect(source).not.toContain("return <SkillsPanel />")
    expect(source).not.toContain("return <McpPanel />")
  })

  test("memory panel sends the active directory on every memory request", () => {
    const source = read("src/components/MemoryPanel.tsx")
    expect(source).toContain("function memoryPath(path: string, directory: string")
    expect(source).toContain('query.set("directory", directory)')
    expect(source).toContain('apiJson(memoryPath("panel/knowledge/memory", directory, { taskID }))')
    expect(source).toContain('apiJson(memoryPath("panel/knowledge/memory/search", directory)')
    expect(source).toContain("memoryPath(`panel/knowledge/memory/${encodeURIComponent(fileId)}`, currentDirectory())")
    expect(source).toContain("if (errorMessage()) return errorMessage()")
    expect(source).toContain("if (!isActive()) return")
    expect(source).not.toContain("if (!isActive() && !props.compact) return")
  })

  test("extension loaders surface request failures instead of rewriting stores to empty values", () => {
    const source = read("src/services/extensions.ts")
    expect(source).toContain("export async function loadInstalledSkills()")
    expect(source).toContain("export async function loadMcpStatus()")
    expect(source).toContain("const [matrix, mcp] = await Promise.all([loadSkillMountMatrix(), loadMcpStatus()])")
    expect(source).toContain("return { skills: matrix.skills, mcp }")
    expect(source).toContain("return skills")
    expect(source).toContain("return mcp")
    expect(source).toContain('apiJson("skill/installed")')
    expect(source).not.toContain('apiJson("skill/installed").catch')
    expect(source).not.toContain('apiJson("skill")')
    expect(source).not.toContain("setSkills([])")
    expect(source).not.toContain("setMcp({})")
    expect(source).not.toContain("setSkillMarket([])")
  })

  test("Skill and MCP panel has one store source and does not swallow destructive MCP failures", () => {
    const source = read("src/components/settings/SkillMarketPanel.tsx")
    expect(source).toContain("const skills = createMemo((): SkillItem[] => [...(appStore.skills")
    expect(source).toContain("const mcp = createMemo((): Record<string, McpItem> => ({ ...(appStore.mcp")
    expect(source).toContain("return await loadSkillMountMatrix({ refresh: options.refresh })")
    expect(source).toContain("await reloadCurrentPanel({ refreshSkills: true })")
    expect(source).toContain("return (await loadMcpStatus()) as Record<string, McpItem>")
    expect(source).toContain("deleteAllSkills,")
    expect(source).toContain("await deleteAllSkills()")
    expect(source).toContain('import { addMcpServer, deleteAllMcp } from "../../services/mcp"')
    expect(source).toContain("await deleteAllMcp()")
    expect(source).not.toContain("panelSkills")
    expect(source).not.toContain("panelMcp")
    expect(source).not.toContain(".catch(() => void 0)")
    expect(source).toContain('nativeConfirm(t("mcp.delete_all_confirm"')
    expect(source).not.toContain("confirm(")
    expect(source).not.toContain("window.confirm")
  })

  test("Skill delete-all uses the extension service and refreshes partial-failure projection", () => {
    const panel = read("src/components/settings/SkillMarketPanel.tsx")
    const service = read("src/services/extensions.ts")
    const start = panel.indexOf("async function handleDeleteAllSkills()")
    const end = panel.indexOf("async function handleDeleteAllMcp()", start)
    const block = panel.slice(start, end)
    expect(block).toContain("await deleteAllSkills()")
    expect(block).not.toContain('apiJson("skill/remove"')
    expect(service).toContain("export async function deleteAllSkills()")
    expect(service).toContain("let removalError: unknown")
    expect(service).toContain("await loadInstalledSkills()")
    expect(service).toContain("if (removalError) throw removalError")
  })

  test("Skill panel convenience actions surface host and API failures", () => {
    const source = read("src/components/settings/SkillMarketPanel.tsx")
    expect(source).toContain("function requireManagedSkillDirectory")
    expect(source).toContain("const target = requireManagedSkillDirectory(dirs)")
    expect(source).toContain('setPanelNotice(t("skill.open_failed"')
    expect(source).toContain('setPanelNotice(t("skill.pick_folder_failed"')
    expect(source).toContain('setPanelNotice(t("skill.open_dir_failed"')
    expect(source).not.toContain("global_config ||")
    expect(source).not.toContain("catch {\n      // ignore")
  })
})
