import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { resolve } from "node:path"

describe("tui host panel wiring", () => {
  test("right activity mounts the OpenTUI renderer-backed embedded panel", () => {
    const main = readFileSync(resolve(import.meta.dir, "../src/main.tsx"), "utf8")
    const plugin = readFileSync(resolve(import.meta.dir, "../src/plugins/coding-agent-tui/index.tsx"), "utf8")
    expect(main).toContain('import { codingAgentTuiPlugin } from "./plugins/coding-agent-tui"')
    expect(main).toContain("const CodingAgentTuiPanel = codingAgentTuiPlugin.Panel")
    expect(main).toContain("rightActivity() === codingAgentTuiPlugin.id")
    expect(main).toContain("directory={activeDirectory}")
    expect(main).not.toContain('import { TuiHostPanel } from "./components/TuiHostPanel"')
    expect(plugin).toContain("Panel: CodingAgentTuiPanel")
    expect(main).not.toContain("TuiRuntimePanel")
  })

  test("panel uses plugin-owned OpenTUI embed frames instead of PTY websocket bytes", () => {
    const panel = readFileSync(resolve(import.meta.dir, "../src/plugins/coding-agent-tui/CodingAgentTuiPanel.tsx"), "utf8")
    const target = readFileSync(resolve(import.meta.dir, "../src/plugins/coding-agent-tui/embedded-target.ts"), "utf8")
    const activityCss = readFileSync(resolve(import.meta.dir, "../src/styles/surfaces/activity.css"), "utf8")
    expect(panel).toContain('from "./embedded-target"')
    expect(panel).toContain("startTuiEmbed({ ...size, directory })")
    expect(panel).toContain("loadTuiEmbedStatus({ directory })")
    expect(panel).toContain("resizeTuiEmbed({ ...nextSize, directory: hostDirectory() })")
    expect(panel).toContain("sendTuiEmbedInput({ ...payload, directory: hostDirectory() })")
    expect(panel).toContain("stopTuiEmbed({ directory: hostDirectory() })")
    expect(panel).toContain("spanStyle(span)")
    expect(panel).toContain("frame().lines")
    expect(panel).toContain("onKeyDown")
    expect(panel).toContain("onPaste")
    expect(panel).toContain("new ResizeObserver")
    expect(panel).toContain("MIN_READABLE_COLS")
    expect(panel).toContain("resizeObserver?.disconnect()")
    expect(panel).not.toContain('import("ghostty-web")')
    expect(panel).not.toContain("new WebSocket")
    expect(panel).not.toContain("buildTuiHostConnectUrl")
    expect(panel).not.toContain("SerializeAddon")
    expect(panel).not.toContain("terminalWriter")
    expect(target).toContain('apiJson(tuiPath("tui/embed/start", input.directory)')
    expect(target).toContain('apiJson(tuiPath("tui/embed/status", input.directory)')
    expect(target).toContain('apiJson(tuiPath("tui/embed/input", input.directory)')
    expect(target).toContain('apiJson(tuiPath("tui/embed/resize", input.directory)')
    expect(target).toContain('apiJson(tuiPath("tui/embed/stop", input.directory)')
    expect(target).toContain('params.set("directory", requireDirectory(directory))')
    expect(target).toContain('agent: TUI_CODING_AGENT')
    expect(target).not.toContain("apiWebSocketUrl")
    expect(target).not.toContain('pty"')
    expect(target).not.toContain("connect-token")
    expect(activityCss).toMatch(/\.tui-host-terminal\s*\{[\s\S]*background:\s*var\(--surface-inset\)/)
    expect(activityCss).toContain("overflow: auto")
    expect(activityCss).not.toContain("background: #0b0b0b")
    expect(activityCss).toContain(".tui-host-frame")
    expect(activityCss).toContain("white-space: pre")
    expect(activityCss).toContain("width: calc(var(--tui-cols) * var(--tui-cell-width))")
    expect(panel).not.toContain("loadTuiRuntimeStatus")
  })
})
