import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { resolve } from "node:path"

describe("tui host panel wiring", () => {
  test("right activity mounts the ghostty-backed embedded host panel", () => {
    const main = readFileSync(resolve(import.meta.dir, "../src/main.tsx"), "utf8")
    expect(main).toContain('import { TuiHostPanel } from "./components/TuiHostPanel"')
    expect(main).toContain('<TuiHostPanel active={() => rightActivity() === "tui"} />')
    expect(main).not.toContain("TuiRuntimePanel")
  })

  test("panel uses ghostty-web with OpenCode-style PTY websocket attach and resize APIs", () => {
    const panel = readFileSync(resolve(import.meta.dir, "../src/components/TuiHostPanel.tsx"), "utf8")
    const serialize = readFileSync(resolve(import.meta.dir, "../src/addons/serialize.ts"), "utf8")
    expect(panel).toContain('import("ghostty-web")')
    expect(panel).toContain('import { SerializeAddon } from "../addons/serialize"')
    expect(panel).toContain('import { terminalWriter } from "../utils/terminal-writer"')
    expect(serialize).toContain("Port of xterm.js addon-serialize for ghostty-web")
    expect(serialize).toContain("export class SerializeAddon")
    expect(serialize).toContain("public serialize(options?: ISerializeOptions): string")
    expect(serialize).toContain("public serializeAsText")
    expect(panel).toContain("new mod.Terminal")
    expect(panel).toContain("new mod.FitAddon")
    expect(panel).toContain("new SerializeAddon()")
    expect(panel).toContain("terminalWriter((data, done)")
    expect(panel).toContain("scheduleTerminalSnapshotSave()")
    expect(panel).toContain("opencorvus:tui-host:${SNAPSHOT_VERSION}:${info.directory}:${info.id}")
    expect(panel).toContain("restoreTerminalSnapshot(current)")
    expect(panel).toContain("saveTerminalSnapshot()")
    expect(panel).toContain("rows: current.rows")
    expect(panel).toContain("cols: current.cols")
    expect(panel).toContain("scrollY: current.getViewportY()")
    expect(panel).toContain("current.resize(parsed.cols, parsed.rows)")
    expect(panel).toContain("current.scrollToLine(parsed.scrollY)")
    expect(panel).toContain("removeTerminalSnapshot()")
    expect(panel).toContain("flushTerminalOutput(finalize)")
    expect(panel).not.toContain("createTuiHostConnectToken")
    expect(panel).toContain("new WebSocket(buildTuiHostConnectUrl")
    expect(panel).toContain("async function reconnectHostSocket()")
    expect(panel).toContain("onClick={() => void reconnectHostSocket()}")
    expect(panel).toContain("closeSocket()")
    expect(panel).toContain("socket.send(data)")
    expect(panel).toContain("resizeTuiHost({ id, cols, rows })")
    expect(panel).toContain("bytes[0] === 0")
    expect(panel).toContain("hostCursor += data.length")
    expect(panel).toContain("if (!term) return")
    expect(panel).not.toContain("sendTuiHostInput(data)")
    expect(panel).not.toContain("loadTuiHostOutput(hostCursor)")
    expect(panel).not.toContain("loadTuiHostSnapshot")
    expect(panel).toContain("new ResizeObserver")
    expect(panel).toContain("resizeObserver?.disconnect()")
    expect(panel).toContain("useTerminalUiBindings({ container, term: next, cleanups, focusTerminal })")
    expect(panel).toContain('input.container.addEventListener("copy", handleCopy, true)')
    expect(panel).toContain('input.container.addEventListener("paste", handlePaste, true)')
    expect(panel).toContain('input.container.addEventListener("pointerdown", handlePointerDown)')
    expect(panel).toContain("input.term.paste(text)")
    expect(panel).toContain("current.textarea?.focus()")
    expect(panel).not.toContain("loadTuiRuntimeStatus")
  })
})
