import { expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"

const OVERLAY_ROOT = join(import.meta.dir, "..")

function readSource(path: string): string {
  return readFileSync(join(OVERLAY_ROOT, path), "utf8")
}

test("left sidebar exposes one unified Work Ledger mount", () => {
  const html = readSource("src/index.html")
  const main = readSource("src/main.tsx")

  expect(html).toContain('id="workLedgerPanel"')
  expect(html).toContain('id="leftPanelWork"')
  expect(html).toContain('data-i18n="work_ledger.title"')
  expect(html).toContain('id="solidLeftPanelActions"')
  expect(html).not.toContain('id="solidLeftActivityToolbar"')
  expect(html).not.toContain('id="leftPanelTasks"')
  expect(html).not.toContain('id="leftPanelMissions"')
  expect(html).not.toContain('id="leftPanelAssistant"')
  expect(html).not.toContain('id="leftPanelMemory"')
  expect(html).not.toContain('id="leftPanelExtensions"')
  expect(html).not.toContain('id="btnCreateTask"')
  expect(html).not.toContain('id="btnCreateMission"')
  expect(html).not.toContain('id="btnCreateCodingAssistantSession"')

  expect(main).toContain('document.getElementById("workLedgerPanel")')
  expect(main).toContain('document.getElementById("solidLeftPanelActions")')
  expect(main).toContain('data-ui="left-panel-open-project"')
  expect(main).toContain('Icon name="project-add"')
  expect(main).toContain('runMainAsync("projects.open-folder", () => browseDirectory())')
  expect(main).toContain("<WorkLedger")
  expect(main).toContain("refreshToken={missionSharedRefreshToken()}")
  expect(main).toContain("setWorkLedgerChangeHandler(() => setMissionSharedRefreshToken((value) => value + 1))")
  expect(main).toMatch(/async function openMissionSession[\s\S]*setMissionSharedRefreshToken\(\(value\) => value \+ 1\)/)
  expect(main).toMatch(/if \(missionSubmitActive\(\)\)[\s\S]*await openMissionSession\(result\)/)
  expect(main).toMatch(/if \(assistantSubmitActive\(\)\)[\s\S]*setMissionSharedRefreshToken\(\(value\) => value \+ 1\)/)
  expect(main).toContain("onSelectMission={(row)")
  expect(main).toContain("onSelectTask={(row)")
  expect(main).toContain("onSelectChat={(row)")
  expect(main).toContain("async function createWorkLedgerProjectChat(directory: string)")
  expect(main).toContain("await createCodingAssistantSession({ directory: projectDirectory })")
  expect(main).toContain('runMainAsync("work-ledger.project-new-chat", () => createWorkLedgerProjectChat(directory))')
  expect(main).not.toContain("<TaskList")
  expect(main).not.toContain("<CodingAssistantSessionList")
  expect(main).not.toContain("<Mission")
  expect(main).not.toContain("type LeftActivity")
  expect(main).not.toContain("LEFT_ACTIVITIES")
})

test("composer mode selector replaces the external executor slot", () => {
  const main = readSource("src/main.tsx")
  const composer = readSource("src/components/ChatComposer.tsx")
  const css = readSource("src/styles/surfaces/composer.css")

  expect(main).toContain('const [primaryCenterPanel, setPrimaryCenterPanel] = createSignal<PrimaryCenterPanel>("chat")')
  expect(main).toContain('const [composerMode, setComposerMode] = createSignal<ComposerMode>("chat")')
  expect(composer).toContain('triggerDataUI="composer-mode-selector"')
  expect(composer).toContain("<SelectControl<ComposerModeOption>")
  expect(composer).toContain('import { ComposerModelSelector } from "./ExecutorSelector"')
  expect(composer).toContain("<ComposerModelSelector />")
  expect(composer).toContain('onComposerModeChange: (mode: ComposerMode) => void')
  expect(composer.indexOf('id: "chat"')).toBeLessThan(composer.indexOf('id: "mission"'))
  expect(composer).toContain("sameWidth={false}")
  expect(composer).toContain("icon={null}")
  expect(composer).not.toContain('import { ExecutorSelector }')
  expect(composer).not.toContain("<ExecutorSelector")
  expect(composer).not.toContain('import * as Select from "@kobalte/core/select"')
  expect(css).toContain(".composer-mode-select-trigger.oc-select-trigger")
})

test("Mission and Task detailed status surfaces keep task-level DAG detail", () => {
  const service = readSource("src/services/mission.ts")

  expect(service).toContain("export async function loadMissionStatus")
  expect(service).toContain("export async function loadTaskStatus")
  expect(service).toContain("agentInvocationDAG: unknown")
})

test("Work Ledger owns row-kind rendering, child task mounting, and row actions", () => {
  const component = readSource("src/components/WorkLedger.tsx")
  const css = readSource("src/styles/surfaces/work-ledger.css")

  expect(component).toContain('data-ui="work-ledger-child-task"')
  expect(component).toContain('data-kind="task"')
  expect(component).toContain("useTaskRowActionsKeyboard")
  expect(component).toContain("function WorkLedgerProjectGroupView")
  expect(component).toContain("const collapsed = () => props.directoryCollapse.isCollapsed(props.group.directory)")
  expect(component).toContain('onCreateChat: (directory: string) => void | Promise<void>')
  expect(component).toContain("onCreateChat={props.onCreateChat}")
  expect(component).toContain("data-actions-keyboard-open={rowActions.actionsKeyboardOpenData()}")
  expect(component).toContain("function taskCanStop(row: WorkLedgerTaskRow): boolean")
  expect(component).toContain("function missionHasVisibleStoppableTask(row: WorkLedgerMissionRow): boolean")
  expect(component).toContain('if (current.kind === "mission") return current.interruptible && !missionHasVisibleStoppableTask(current)')
  expect(component).toContain('data-ui="task-row-start-now"')
  expect(component).toContain('data-ui={stopDataUi()}')
  expect(component).toContain('data-ui="task-row-download"')
  expect(component).toContain('data-ui="task-row-rename"')
  expect(component).toContain("dataUi={deleteDataUi()}")
  expect(component).toContain('props.children ?? <Icon name="delete" size={11} />')
  expect(component).not.toContain('props.children ?? <Icon name="close" size={11} />')
  expect(component).toContain('return row().kind === "task" ? "task-row-cancel" : "work-row-stop"')
  expect(component).toContain('return row().kind === "task" ? "task-row-delete" : "work-row-delete"')
  expect(component).toContain("<WorkLedgerTaskChildRow")
  expect(component).toContain("onStartTask={props.onStartTask}")
  expect(component).toContain("onDownloadTask={props.onDownloadTask}")
  expect(component).toContain("onRenameTask={props.onRenameTask}")
  expect(component).toContain("function inlineMeta")
  expect(component).toContain('class="work-row-inline-meta"')
  expect(component).not.toContain('class="work-row-meta"')
  expect(component).not.toContain('kindLabel("chat")')
  expect(component).not.toContain("const collapsed = directoryCollapse.isCollapsed(group.directory)")

  expect(css).toContain(".work-row-kind-mark")
  expect(css).toContain(".work-row-status-mark")
  expect(css).toContain(".work-row-inline-meta")
  expect(css).toMatch(/\.work-row-main\s*\{[^}]*flex-direction:\s*row;/)
  expect(css).not.toContain(".work-row-meta")
  expect(css).not.toMatch(/\.work-row-main\s*\{[^}]*flex-direction:\s*column;/)
  expect(css).toMatch(/\.work-row \.task-row-actions\.work-row-actions\s*\{[^}]*position:\s*static;/)
  expect(css).toMatch(/\.work-row \.task-row-actions\.work-row-actions\s*\{[^}]*transform:\s*none;/)
  expect(css).toMatch(/\.work-row \.task-row-actions\.work-row-actions\s*\{[^}]*flex:\s*0 0 0;/)
  expect(css).toMatch(/\.work-row \.task-row-actions\.work-row-actions\s*\{[^}]*gap:\s*var\(--work-row-action-gap\);/)
  expect(css).toMatch(/\.work-row:hover \.task-row-actions\.work-row-actions,[\s\S]*flex-basis:\s*var\(--task-row-actions-width\);/)
  expect(css).toMatch(
    /\.work-row:hover \.task-row-actions\.work-row-actions,[\s\S]*padding:\s*0 var\(--work-row-action-rail-pad\);/,
  )
  expect(css).toContain("--work-row-action-size: calc(22px * var(--ui-scale));")
  expect(css).toContain("--work-row-action-gap: calc(4px * var(--ui-scale));")
  expect(css).toContain("--work-row-action-rail-pad: calc(4px * var(--ui-scale));")
  expect(css).toContain('.work-row[data-action-count="2"]')
  expect(css).toContain('.work-row[data-action-count="3"]')
  expect(css).toContain('.work-row[data-action-count="5"]')
  expect(css).toMatch(/\.work-row\[data-action-count="3"\]\s*\{[^}]*--task-row-actions-width:\s*calc\(82px \* var\(--ui-scale\)\);/)
  expect(css).toMatch(/\.work-row\[data-action-count="5"\]\s*\{[^}]*--task-row-actions-width:\s*calc\(134px \* var\(--ui-scale\)\);/)
  expect(css).toMatch(/\.work-row:hover \.work-row-right,[\s\S]*gap:\s*0;/)
  expect(css).toMatch(/\.work-row:hover \.work-row-status-mark,[\s\S]*max-width:\s*0;/)
  expect(css).toMatch(/\.work-row:hover \.work-row-status-mark,[\s\S]*flex:\s*0 0 0;/)
  expect(css).toMatch(/\.work-row:hover \.work-row-inline-meta,[\s\S]*max-width:\s*0;/)
  expect(css).toContain('.work-row-actions .oc-button[data-chrome="icon-action"][data-ui="work-row-stop"]')
  expect(css).toContain('.work-row-actions .oc-button[data-chrome="icon-action"][data-ui="work-row-delete"]')
  expect(css).toContain('.work-row-actions .oc-button[data-chrome="icon-action"][data-ui="task-row-start-now"]')
  expect(css).toContain('.work-row-actions .oc-button[data-chrome="icon-action"][data-ui="task-row-cancel"]')
  expect(css).toContain('.work-row-actions .oc-button[data-chrome="icon-action"][data-ui="task-row-download"]')
  expect(css).toContain('.work-row-actions .oc-button[data-chrome="icon-action"][data-ui="task-row-rename"]')
  expect(css).toContain('.work-row-actions .oc-button[data-chrome="icon-action"][data-ui="task-row-delete"]')
  expect(css).toMatch(/--oc-button-height:\s*var\(--work-row-action-size\);/)
  expect(css).toMatch(/width:\s*var\(--work-row-action-size\);/)
  expect(css).not.toMatch(
    /\.work-row-actions \.oc-button\[data-ui="task-row-cancel"\] svg \*\s*\{[^}]*fill:\s*currentColor;[^}]*stroke:\s*none;/,
  )
  expect(css).not.toMatch(
    /\.work-row:hover \.work-row-actions \.oc-button\[data-ui="work-row-stop"\],[\s\S]*?\.work-row\[data-actions-keyboard-open="true"\] \.work-row-actions \.oc-button\[data-ui="task-row-cancel"\]\s*\{[^}]*--oc-button-color:\s*var\(--warn\);/,
  )
  expect(css).toMatch(/\.work-row-actions \.oc-button\[data-ui="work-row-stop"\]:hover,[\s\S]*?--oc-button-color:\s*var\(--warn\);/)
})

test("Work Ledger main wiring restores task action services", () => {
  const main = readSource("src/main.tsx")

  expect(main).toContain("renameTask")
  expect(main).toContain("downloadTaskProjectArchive")
  expect(main).toContain("startQueuedTaskNow")
  expect(main).toContain("async function startWorkLedgerTask(row: WorkLedgerTaskRow)")
  expect(main).toContain("async function downloadWorkLedgerTask(row: WorkLedgerTaskRow)")
  expect(main).toContain("async function renameWorkLedgerTask(row: WorkLedgerTaskRow)")
  expect(main).toContain("onStartTask={(row) => startWorkLedgerTask(row)}")
  expect(main).toContain("onDownloadTask={(row) => downloadWorkLedgerTask(row)}")
  expect(main).toContain("onRenameTask={(row) => renameWorkLedgerTask(row)}")
})
