import { expect, test } from "bun:test"

test("orchestrator workflow treats deliver as verdict evidence, not a host-forced stop", async () => {
  const prompt = await Bun.file(new URL("../../src/prompt/core/orchestrator-core.txt", import.meta.url)).text()
  const agent = await Bun.file(new URL("../../src/orchestrator/agent.ts", import.meta.url)).text()
  const workflow = await Bun.file(new URL("../../src/engine/workflow.ts", import.meta.url)).text()
  const tools = await Bun.file(new URL("../../src/orchestrator/tools.ts", import.meta.url)).text()
  const normalizedPrompt = prompt.replace(/\s+/g, " ")

  expect(normalizedPrompt).toContain("Rejected `deliver` returns evidence for the next orchestrator decision")
  expect(prompt).toContain("assistant.auto_iteration=false")
  expect(prompt).toContain("assistant.auto_iteration=true")
  expect(normalizedPrompt).toContain("not a host-side mandate to end the scheduler")
  expect(prompt).toContain("Accepted deliveries complete the task inside the tool")
  expect(normalizedPrompt).toContain("Valid next actions include task-level build")
  expect(normalizedPrompt).toContain("the host will not open rework attempts or queue repair work by itself")
  expect(prompt).not.toContain("default scheduler endpoint")
  expect(prompt).not.toContain("Stop\nthe scheduler when `deliver` returns")

  expect(workflow).toContain("deliver 是唯一接受闸")
  expect(workflow).toContain("Rejected 返回结构化证据")
  expect(workflow).not.toContain("deliver 是默认调度终点")
  expect(workflow).not.toContain("停止调度")

  expect(agent).toContain("## Auto Iteration Mode")
  expect(agent).toContain("assistant.auto_iteration=false: rejected deliveries and failed terminal waves do not open host-side rework attempts")
  expect(agent).toContain("The current reasoning turn still owns the next decision")
  expect(agent).toContain("assistant.auto_iteration=true: rejected deliveries")
  expect(agent).not.toContain("withStepHook")
  expect(agent).not.toContain("stopSignal")

  expect(tools).toContain("the host did not request a scheduler stop")
  expect(tools).toContain("const autoIteration = (await EngineConfig.get()).auto_iteration === true")
  expect(tools).toContain("if (autoIteration)")
  expect(tools).not.toContain("requestStopAfterCurrentStep")
  expect(tools).not.toContain("finalizeDeferredStop")
  expect(tools).not.toContain("stopAfterDispatch")
  expect(tools).toContain("dispatchTaskLoop({")
  expect(tools).toContain("continue with follow-up questions or further changes in this task")
  expect(tools).not.toContain("You can call refine to analyze the project and suggest improvements for the next iteration.")
})
