#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@opencorvus-ai/script"
import pkg from "../package.json"

const protocol = path.resolve(dir, "..", "..", "scripts", "generate-overlay-protocol.ts")
await $`${process.execPath} ${protocol}`
console.log("Generated overlay protocol")

const modelsUrl = process.env.OPENCORVUS_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const allFlag = process.argv.includes("--all")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const binaryOnly = process.argv.includes("--binary-only")
const onefileFlag = process.argv.includes("--onefile") || process.env.OPENCORVUS_ONEFILE === "1"

const embeddedEnv = (() => {
  const keys = (process.env.OPENCORVUS_EMBED_ENV_KEYS ?? "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean)
  const env = Object.fromEntries(
    keys.flatMap((key) => {
      const value = process.env[key]?.trim()
      if (!value) return []
      return [[key, value] as const]
    }),
  ) as Record<string, string>

  const dashscope = process.env.OPENCORVUS_EMBED_DASHSCOPE_KEY?.trim()
  if (dashscope) {
    env.OPENCORVUS_EMBEDDED_DASHSCOPE_KEY = dashscope
    env.OPENCORVUS_EMBEDDED_DASHSCOPE_TTL_HOURS = process.env.OPENCORVUS_EMBED_DASHSCOPE_TTL_HOURS?.trim() || "24"
    if (!env.OPENCORVUS_CONFIG_CONTENT && !process.env.OPENCORVUS_CONFIG_CONTENT) {
      env.OPENCORVUS_CONFIG_CONTENT = JSON.stringify({
        $schema: "https://opencode.ai/config.json",
        model: "alibaba-cn/qwen3.5-plus",
      })
    }
  }

  const model = process.env.OPENCORVUS_EMBED_MODEL?.trim()
  if (model) {
    env.OPENCORVUS_CONFIG_CONTENT = JSON.stringify({
      $schema: "https://opencode.ai/config.json",
      model,
    })
  }

  return env
})()

if (Object.keys(embeddedEnv).length > 0) {
  console.log(`embedding env keys: ${Object.keys(embeddedEnv).join(", ")}`)
}
const embeddedEnvDefine = Object.keys(embeddedEnv).length > 0 ? JSON.stringify(embeddedEnv) : "undefined"
if (onefileFlag) {
  console.log("onefile mode enabled: embedding overlay sidecar into main binary")
}

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]
const runtimeDir = process.env.OPENCORVUS_BUN_RUNTIME_DIR
const runtimeName = (item: (typeof allTargets)[number]) =>
  [
    "bun",
    item.os === "win32" ? "windows" : item.os,
    item.arch === "arm64" ? "aarch64" : item.arch,
    item.abi,
    item.avx2 === false ? "baseline" : undefined,
  ]
    .filter(Boolean)
    .join("-")
type Target = (typeof allTargets)[number]

const overlayRequired = process.env.OPENCORVUS_OVERLAY_REQUIRED !== "0"
const overlayDir = process.env.OPENCORVUS_OVERLAY_BIN_DIR?.trim()
const overlayGlobal = process.env.OPENCORVUS_OVERLAY_BIN?.trim()
const overlayManifest = path.resolve(dir, "..", "overlay", "src-tauri", "Cargo.toml")
let overlayBuildAttempted = false

function overlayOS(item: Target) {
  return item.os === "win32" ? "windows" : item.os
}

function overlayExt(item: Target) {
  return item.os === "win32" ? ".exe" : ""
}

function overlayBaseName(item: Target) {
  return `opencorvus-overlay${overlayExt(item)}`
}

function overlayLabel(item: Target) {
  return [overlayOS(item), item.arch, item.abi].filter(Boolean).join("-")
}

function overlayEnvKey(item: Target) {
  return `OPENCORVUS_OVERLAY_BIN_${[overlayOS(item), item.arch, item.abi].filter(Boolean).join("_").toUpperCase()}`
}

function overlayNames(item: Target) {
  const ext = overlayExt(item)
  const os = overlayOS(item)
  return [...new Set([
    `opencorvus-overlay-${os}-${item.arch}${item.abi ? `-${item.abi}` : ""}${ext}`,
    `opencorvus-overlay-${os}-${item.arch}${ext}`,
    overlayBaseName(item),
  ])]
}

function localOverlay(item: Target) {
  if (item.os !== process.platform || item.arch !== process.arch) return false
  if (item.abi !== undefined) return false
  return true
}

async function ensureOverlayBuilt() {
  if (overlayBuildAttempted) return
  overlayBuildAttempted = true
  const cargo = Bun.which("cargo")
  if (!cargo) return
  console.log("building local overlay sidecar")
  await $`${cargo} build --release --manifest-path ${overlayManifest}`
}

async function resolveOverlay(item: Target) {
  const key = overlayEnvKey(item)
  const exact = process.env[key]?.trim()
  if (exact) {
    if (!fs.existsSync(exact)) {
      throw new Error(`Overlay sidecar from ${key} does not exist: ${exact}`)
    }
    return exact
  }

  if (overlayGlobal) {
    if (!fs.existsSync(overlayGlobal)) {
      throw new Error(`Overlay sidecar from OPENCORVUS_OVERLAY_BIN does not exist: ${overlayGlobal}`)
    }
    return overlayGlobal
  }

  if (overlayDir) {
    for (const name of overlayNames(item)) {
      const candidate = path.resolve(overlayDir, name)
      if (fs.existsSync(candidate)) return candidate
    }
  }

  if (!localOverlay(item)) return null

  const ext = overlayExt(item)
  const release = path.resolve(dir, "..", "overlay", "src-tauri", "target", "release", `opencorvus-overlay${ext}`)
  const debug = path.resolve(dir, "..", "overlay", "src-tauri", "target", "debug", `opencorvus-overlay${ext}`)
  if (fs.existsSync(release)) return release
  if (fs.existsSync(debug)) return debug

  await ensureOverlayBuilt()
  if (fs.existsSync(release)) return release
  if (fs.existsSync(debug)) return debug
  return null
}

async function installOverlay(item: Target, name: string) {
  const from = await resolveOverlay(item)
  if (!from) {
    const key = overlayEnvKey(item)
    const hint = [
      `missing overlay sidecar for target ${overlayLabel(item)}`,
      `set ${key}=<path> or set OPENCORVUS_OVERLAY_BIN_DIR=<dir> with one of: ${overlayNames(item).join(", ")}`,
      `or disable strict mode with OPENCORVUS_OVERLAY_REQUIRED=0`,
    ].join(" | ")
    if (overlayRequired) throw new Error(hint)
    console.warn(hint)
    return
  }

  const file = path.join(dir, "dist", name, "bin", overlayBaseName(item))
  await fs.promises.copyFile(from, file)
  if (item.os !== "win32") {
    await fs.promises.chmod(file, 0o755)
  }
  console.log(`embedded overlay ${path.basename(from)} -> dist/${name}/bin/${overlayBaseName(item)}`)
}

// Dev and CI builds only need a native binary; full matrix is for release packaging.
const single = singleFlag || (!allFlag && !Script.release)
const targets = single
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`.nothrow()

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")
  const executablePath = runtimeDir
    ? path.resolve(runtimeDir, runtimeName(item), item.os === "win32" ? "bun.exe" : "bun")
    : undefined
  if (runtimeDir && executablePath && !fs.existsSync(executablePath)) {
    throw new Error(`Missing Bun runtime for target '${runtimeName(item)}' at '${executablePath}'`)
  }

  const compile: Record<string, unknown> = {
    autoloadBunfig: false,
    autoloadDotenv: false,
    autoloadTsconfig: true,
    autoloadPackageJson: true,
    target: name.replace(pkg.name, "bun"),
    outfile: `dist/${name}/bin/opencorvus`,
    execArgv: [`--user-agent=opencorvus/${Script.version}`, "--use-system-ca", "--"],
    windows: {},
  }
  if (executablePath) compile.executablePath = executablePath

  const overlaySource = onefileFlag ? await resolveOverlay(item) : null
  if (onefileFlag && !overlaySource) {
    throw new Error(`onefile mode requires overlay sidecar for target ${overlayLabel(item)}`)
  }
  const overlayBytes = overlaySource ? await Bun.file(overlaySource).bytes() : undefined
  const embeddedOverlayDefine = overlayBytes
    ? JSON.stringify(Buffer.from(overlayBytes).toString("base64"))
    : "undefined"
  const embeddedOverlayHashDefine = overlayBytes
    ? JSON.stringify(Bun.hash.xxHash32(overlayBytes).toString(16).padStart(8, "0"))
    : "undefined"

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: binaryOnly ? "none" : "external",
    compile: compile as any,
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCORVUS_VERSION: `'${Script.version}'`,
      OPENCORVUS_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCORVUS_WORKER_PATH: workerPath,
      OPENCORVUS_CHANNEL: `'${Script.channel}'`,
      OPENCORVUS_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      OPENCORVUS_EMBEDDED_ENV: embeddedEnvDefine,
      OPENCORVUS_EMBEDDED_OVERLAY_B64: embeddedOverlayDefine,
      OPENCORVUS_EMBEDDED_OVERLAY_HASH: embeddedOverlayHashDefine,
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  if (!onefileFlag) await installOverlay(item, name)
  if (binaryOnly) {
    const files = await fs.promises.readdir(path.join(dir, "dist", name, "bin"))
    await Promise.all(
      files
        .filter((x) => x.endsWith(".map"))
        .map((x) => fs.promises.rm(path.join(dir, "dist", name, "bin", x), { force: true })),
    )
  }
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }

