#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@opencorvus-ai/script"
import pkg from "../package.json"

const modelsUrl = process.env.OPENCORVUS_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

const singleFlag = process.argv.includes("--single")
const allFlag = process.argv.includes("--all")
const baselineFlag = process.argv.includes("--baseline")
const muslOnly = process.argv.includes("--musl-only")
const noClean = process.argv.includes("--no-clean")
const binaryOnly = process.argv.includes("--binary-only")
const embeddedEnv = (() => {
  const keys = (process.env.OPENCORVUS_EMBED_ENV_KEYS ?? "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean)
  const env = Object.fromEntries(
    keys.flatMap((key) => {
      const value = process.env[key]?.trim()
      if (!value) return []
      return [[key, value] as const]
    }),
  ) as Record<string, string>

  const dashscope = process.env.OPENCORVUS_EMBED_DASHSCOPE_KEY?.trim()
  if (dashscope) {
    env.OPENCORVUS_EMBEDDED_DASHSCOPE_KEY = dashscope
    env.OPENCORVUS_EMBEDDED_DASHSCOPE_TTL_HOURS = process.env.OPENCORVUS_EMBED_DASHSCOPE_TTL_HOURS?.trim() || "24"
    if (!env.OPENCORVUS_CONFIG_CONTENT && !process.env.OPENCORVUS_CONFIG_CONTENT) {
      env.OPENCORVUS_CONFIG_CONTENT = JSON.stringify({
        $schema: "https://opencorvus.ai/config.json",
        model: "alibaba-cn/qwen3.5-plus",
      })
    }
  }

  const model = process.env.OPENCORVUS_EMBED_MODEL?.trim()
  if (model) {
    env.OPENCORVUS_CONFIG_CONTENT = JSON.stringify({
      $schema: "https://opencorvus.ai/config.json",
      model,
    })
  }

  return env
})()

if (Object.keys(embeddedEnv).length > 0) {
  console.log(`embedding env keys: ${Object.keys(embeddedEnv).join(", ")}`)
}
const embeddedEnvDefine = Object.keys(embeddedEnv).length > 0 ? JSON.stringify(embeddedEnv) : "undefined"
const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]
const runtimeDir = process.env.OPENCORVUS_BUN_RUNTIME_DIR
const runtimeName = (item: (typeof allTargets)[number]) =>
  [
    "bun",
    item.os === "win32" ? "windows" : item.os,
    item.arch === "arm64" ? "aarch64" : item.arch,
    item.abi,
    item.avx2 === false ? "baseline" : undefined,
  ]
    .filter(Boolean)
    .join("-")
type Target = (typeof allTargets)[number]

// Dev and CI builds only need a native binary; full matrix is for release packaging.
const single = singleFlag || (!allFlag && !Script.release)
const targets = single
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // --musl-only: build only musl abi variants (used in Alpine Docker for correct native modules)
      if (muslOnly) {
        return item.abi === "musl" && (item.avx2 !== false || baselineFlag)
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

if (!noClean) await $`rm -rf dist`.nothrow()

const binaries: Record<string, string> = {}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")
  const executablePath = runtimeDir
    ? path.resolve(runtimeDir, runtimeName(item), item.os === "win32" ? "bun.exe" : "bun")
    : undefined
  if (runtimeDir && executablePath && !fs.existsSync(executablePath)) {
    throw new Error(`Missing Bun runtime for target '${runtimeName(item)}' at '${executablePath}'`)
  }

  const compile: Record<string, unknown> = {
    autoloadBunfig: false,
    autoloadDotenv: false,
    autoloadTsconfig: true,
    autoloadPackageJson: true,
    target: name.replace(pkg.name, "bun"),
    outfile: `dist/${name}/opencorvus`,
    execArgv: [`--user-agent=opencorvus/${Script.version}`, "--use-system-ca", "--"],
    windows: {},
  }
  if (executablePath) compile.executablePath = executablePath

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: binaryOnly ? "none" : "external",
    compile: compile as any,
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCORVUS_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCORVUS_WORKER_PATH: workerPath,
      OPENCORVUS_CHANNEL: `'${Script.channel}'`,
      OPENCORVUS_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      OPENCORVUS_EMBEDDED_ENV: embeddedEnvDefine,
    },
  })

  await $`rm -rf ./dist/${name}/tui`
  if (binaryOnly) {
    const files = await fs.promises.readdir(path.join(dir, "dist", name))
    await Promise.all(
      files
        .filter((x) => x.endsWith(".map"))
        .map((x) => fs.promises.rm(path.join(dir, "dist", name, x), { force: true })),
    )
  }
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../${key}.tar.gz *`.cwd(`dist/${key}`)
    } else {
      await $`zip -r ../${key}.zip *`.cwd(`dist/${key}`)
    }
  }
  const files = [
    ...new Bun.Glob("dist/*.zip").scanSync("."),
    ...new Bun.Glob("dist/*.tar.gz").scanSync("."),
  ]
  if (files.length === 0) {
    throw new Error("No release archives found in dist/")
  }
  await $`gh release upload v${Script.version} ${files} --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
