#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import os from "os"
import { fileURLToPath } from "url"
import { createRequire } from "module"
import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@opencorvus-ai/script"
import pkg from "../package.json"
import { selectBuildTargets, type BuildTarget } from "./build-targets"
import {
  artifactBrowserMcpNodeExternalModules,
  artifactBrowserMcpNodeExecutableName,
  artifactEntrypoints,
  artifactExternalModules,
  artifactHostCanProvideNodeRuntime,
  artifactPackageBaseName,
  artifactSourcemap,
  parseBuildFlavor,
} from "./build-artifact"
import { detectArtifactNodeRuntimeHost } from "./build-host-runtime"

const modelsUrl = process.env.OPENCORVUS_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

const singleFlag = process.argv.includes("--single")
const allFlag = process.argv.includes("--all")
const baselineFlag = process.argv.includes("--baseline")
const binaryOnly = process.argv.includes("--binary-only")
const buildFlavor = parseBuildFlavor(process.argv)
// --musl-only selects abi-tagged targets (musl) for the current arch
// instead of the default glibc set. Used by the Linux docker step in
// .github/workflows/build.yml, which runs inside `oven/bun:alpine` and
// is responsible for producing the musl variants alongside the host's
// glibc artifacts.
const muslOnlyFlag = process.argv.includes("--musl-only")
// --no-clean skips the `rm -rf dist` step so a follow-up single-target
// invocation (e.g. the musl docker step running after the glibc step)
// can augment an existing dist/ without wiping the earlier artifacts.
const noCleanFlag = process.argv.includes("--no-clean")

const embeddedEnv = (() => {
  const keys = (process.env.OPENCORVUS_EMBED_ENV_KEYS ?? "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean)
  const env = Object.fromEntries(
    keys.flatMap((key) => {
      const value = process.env[key]?.trim()
      if (!value) return []
      return [[key, value] as const]
    }),
  ) as Record<string, string>

  const dashscope = process.env.OPENCORVUS_EMBED_DASHSCOPE_KEY?.trim()
  if (dashscope) {
    env.OPENCORVUS_EMBEDDED_DASHSCOPE_KEY = dashscope
    env.OPENCORVUS_EMBEDDED_DASHSCOPE_TTL_HOURS = process.env.OPENCORVUS_EMBED_DASHSCOPE_TTL_HOURS?.trim() || "24"
    if (!env.OPENCORVUS_CONFIG_CONTENT && !process.env.OPENCORVUS_CONFIG_CONTENT) {
      env.OPENCORVUS_CONFIG_CONTENT = JSON.stringify({
        $schema: "https://opencorvus.ai/config.json",
        model: "alibaba-cn/qwen3.5-plus",
      })
    }
  }

  const model = process.env.OPENCORVUS_EMBED_MODEL?.trim()
  if (model) {
    env.OPENCORVUS_CONFIG_CONTENT = JSON.stringify({
      $schema: "https://opencorvus.ai/config.json",
      model,
    })
  }

  return env
})()

if (Object.keys(embeddedEnv).length > 0) {
  console.log(`embedding env keys: ${Object.keys(embeddedEnv).join(", ")}`)
}
const embeddedEnvDefine = Object.keys(embeddedEnv).length > 0 ? JSON.stringify(embeddedEnv) : "undefined"

const allTargets: BuildTarget[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]
const runtimeDir = process.env.OPENCORVUS_BUN_RUNTIME_DIR
const runtimeName = (item: (typeof allTargets)[number]) =>
  [
    "bun",
    item.os === "win32" ? "windows" : item.os,
    item.arch === "arm64" ? "aarch64" : item.arch,
    item.abi,
    item.avx2 === false ? "baseline" : undefined,
  ]
    .filter(Boolean)
    .join("-")
type Target = (typeof allTargets)[number]

// Dev and CI builds only need a native binary; full matrix is for release packaging.
const single = singleFlag || (!allFlag && !Script.release)
const targets = selectBuildTargets(allTargets, {
  platform: process.platform,
  arch: process.arch,
  single,
  baseline: baselineFlag,
  muslOnly: muslOnlyFlag,
})

if (single && targets.length === 0) {
  throw new Error(
    `build.ts: no targets matched for ${process.platform}-${process.arch}` +
      ` (single=${single}, baseline=${baselineFlag}, muslOnly=${muslOnlyFlag}). ` +
      `Check the workflow flags and the allTargets table.`,
  )
}

if (!noCleanFlag) {
  await $`rm -rf dist`.nothrow()
}

const binaries: Record<string, string> = {}
let windowsSupervisorHelper: string | undefined
const requireFromPackage = createRequire(path.join(dir, "package.json"))

async function buildWindowsSupervisorHelper() {
  if (windowsSupervisorHelper) return windowsSupervisorHelper
  if (process.platform !== "win32") {
    throw new Error("Windows process supervisor helper must be built on Windows")
  }
  const manifest = path.join(dir, "native", "process-supervisor", "Cargo.toml")
  await $`cargo build --manifest-path ${manifest} --release`
  windowsSupervisorHelper = path.join(dir, "native", "process-supervisor", "target", "release", "opencorvus-process-supervisor.exe")
  if (!fs.existsSync(windowsSupervisorHelper)) {
    throw new Error(`Missing Windows process supervisor helper at ${windowsSupervisorHelper}`)
  }
  return windowsSupervisorHelper
}

async function buildBrowserMcpNodeBundle(outdir: string) {
  await fs.promises.mkdir(outdir, { recursive: true })
  const result = await Bun.build({
    entrypoints: ["./src/mcp/browser/stdio.ts"],
    outdir,
    target: "node",
    external: artifactBrowserMcpNodeExternalModules(),
  })
  if (!result.success) {
    const detail = result.logs.map((item) => item.message).join("; ")
    throw new Error(`Failed to build Browser MCP node bundle: ${detail}`)
  }
  await fs.promises.rename(path.join(outdir, "stdio.js"), path.join(outdir, "stdio.mjs"))
}

async function copyPackageDirectory(source: string, destination: string) {
  await fs.promises.rm(destination, { recursive: true, force: true })
  await fs.promises.cp(source, destination, {
    recursive: true,
    dereference: true,
    filter: (entry) => {
      const rel = path.relative(source, entry)
      return rel === "" || !rel.split(path.sep).includes("node_modules")
    },
  })
}

async function copyBrowserMcpNodeModules(outdir: string) {
  const playwrightPackageJson = requireFromPackage.resolve("playwright/package.json")
  const playwrightDir = path.dirname(playwrightPackageJson)
  const requireFromPlaywright = createRequire(path.join(playwrightDir, "index.js"))
  const playwrightCorePackageJson = requireFromPlaywright.resolve("playwright-core/package.json")
  const packages = [
    ["playwright", playwrightDir],
    ["playwright-core", path.dirname(playwrightCorePackageJson)],
  ] as const
  const nodeModules = path.join(outdir, "node_modules")
  await fs.promises.mkdir(nodeModules, { recursive: true })
  for (const [name, source] of packages) {
    await copyPackageDirectory(source, path.join(nodeModules, name))
  }
}

function findExecutableOnPath(name: string) {
  const paths = (process.env.PATH ?? "").split(path.delimiter).filter(Boolean)
  const extensions =
    process.platform === "win32" ? (process.env.PATHEXT ?? ".EXE;.CMD;.BAT").split(";").filter(Boolean) : [""]
  for (const dir of paths) {
    for (const ext of extensions) {
      const candidate = path.join(dir, name.endsWith(ext.toLowerCase()) || name.endsWith(ext) ? name : `${name}${ext}`)
      if (fs.existsSync(candidate)) return candidate
    }
  }
}

async function copyBrowserMcpNodeRuntime(item: Target, outdir: string) {
  const nodeName = artifactBrowserMcpNodeExecutableName(item.os)
  const explicit = process.env.OPENCORVUS_BROWSER_MCP_NODE_BUILD_PATH?.trim()
  const host = explicit ? undefined : await detectArtifactNodeRuntimeHost()
  const source = explicit || (host && artifactHostCanProvideNodeRuntime(item, host) ? findExecutableOnPath(nodeName) : undefined)
  if (!source) {
    throw new Error(
      `Missing Browser MCP Node runtime for target ${runtimeName(item)}. ` +
        `Build on the target platform or set OPENCORVUS_BROWSER_MCP_NODE_BUILD_PATH to a ${nodeName} executable.`,
    )
  }
  const destination = path.join(outdir, nodeName)
  await fs.promises.copyFile(source, destination)
  if (item.os !== "win32") {
    await fs.promises.chmod(destination, 0o755)
  }
}

for (const item of targets) {
  const compileTarget = [
    "bun",
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  const name = [
    artifactPackageBaseName(pkg.name, buildFlavor),
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")
  const executablePath = runtimeDir
    ? path.resolve(runtimeDir, runtimeName(item), item.os === "win32" ? "bun.exe" : "bun")
    : undefined
  if (runtimeDir && executablePath && !fs.existsSync(executablePath)) {
    throw new Error(`Missing Bun runtime for target '${runtimeName(item)}' at '${executablePath}'`)
  }

  const compile: Record<string, unknown> = {
    autoloadBunfig: false,
    autoloadDotenv: false,
    autoloadTsconfig: true,
    autoloadPackageJson: true,
    target: compileTarget,
    outfile: `dist/${name}/opencorvus`,
    execArgv: [`--user-agent=opencorvus/${Script.version}`, "--use-system-ca", "--"],
    windows: {},
  }
  if (executablePath) compile.executablePath = executablePath

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: artifactSourcemap(),
    external: artifactExternalModules(),
    compile: compile as any,
    entrypoints: artifactEntrypoints(buildFlavor, parserWorker, workerPath),
    define: {
      OPENCORVUS_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCORVUS_WORKER_PATH: workerPath,
      OPENCORVUS_CHANNEL: `'${Script.channel}'`,
      OPENCORVUS_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      OPENCORVUS_EMBEDDED_ENV: embeddedEnvDefine,
    },
  })
  const browserMcpRuntimeDir = path.join(dir, "dist", name, "browser-mcp-node")
  await buildBrowserMcpNodeBundle(browserMcpRuntimeDir)
  await copyBrowserMcpNodeModules(browserMcpRuntimeDir)
  await copyBrowserMcpNodeRuntime(item, browserMcpRuntimeDir)

  if (item.os === "win32") {
    const helper = await buildWindowsSupervisorHelper()
    await fs.promises.copyFile(helper, path.join(dir, "dist", name, "opencorvus-process-supervisor.exe"))
  }

  await $`rm -rf ./dist/${name}/tui`
  if (binaryOnly) {
    const files = await fs.promises.readdir(path.join(dir, "dist", name))
    await Promise.all(
      files
        .filter((x) => x.endsWith(".map"))
        .map((x) => fs.promises.rm(path.join(dir, "dist", name, x), { force: true })),
    )
  }
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

export { binaries }
