import path from "path"
import { resolveModelsSnapshotData } from "./models-snapshot"
import { generateExpertSquadPayloadModule } from "./generate-expert-squad-payload"

export async function generateOpencorvusGeneratedBuildArtifacts(input: {
  packageRoot?: string
  repoRoot?: string
  modelsUrl?: string
  log?: (message: string) => void
} = {}) {
  const packageRoot = input.packageRoot ?? path.resolve(import.meta.dir, "..")
  const repoRoot = input.repoRoot ?? path.resolve(packageRoot, "../..")
  const modelsUrl = input.modelsUrl ?? process.env.OPENCORVUS_MODELS_URL ?? "https://models.dev"
  const modelsSnapshotPath = path.join(packageRoot, "src/provider/models-snapshot.ts")
  const log = input.log ?? (() => {})

  await generateExpertSquadPayloadModule(repoRoot)
  log("Generated expert-squad payload module")

  const modelsData = await resolveModelsSnapshotData({ modelsSnapshotPath, modelsUrl })
  await Bun.write(
    modelsSnapshotPath,
    `// Auto-generated by generate-build-artifacts.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
  )
  log("Generated models-snapshot.ts")
}
