// Generated by scripts/generate-overlay-protocol.ts. Do not edit manually.
#![allow(dead_code)]
pub const WINDOW_OVERLAY: &str = "overlay";
pub const WINDOW_HIGHLIGHT: &str = "window-highlight";
pub const WINDOW_CONFIRM: &str = "confirm";
pub const WINDOW_CONSOLE: &str = "console";

pub const EVT_SHOW_OVERLAY: &str = "show-overlay";
pub const EVT_SHOW_CONFIRM: &str = "show-confirm";
pub const EVT_SHOW_WINDOW_HIGHLIGHT: &str = "show-window-highlight";
pub const EVT_MANAGER_LOG: &str = "manager-log";
pub const EVT_MANAGER_STATE: &str = "manager-state";
pub const EVT_MANAGER_CHAT: &str = "manager-chat";
pub const EVT_OVERLAY_DIAGNOSTIC: &str = "overlay-diagnostic";

pub const MSG_HINT: &str = "hint";
pub const MSG_CONFIRM: &str = "confirm";
pub const MSG_WINDOW_HIGHLIGHT: &str = "window-highlight";
pub const MSG_DIAGNOSTIC: &str = "diagnostic";
pub const MSG_CONFIRM_REPLY: &str = "confirm-reply";

pub const CMD_POSITION_WINDOW: &str = "position_window";
pub const CMD_HIDE_WINDOW: &str = "hide_window";
pub const CMD_CONFIRM_REPLY: &str = "confirm_reply";
pub const CMD_MANAGER_OPEN: &str = "manager_open";
pub const CMD_MANAGER_GET: &str = "manager_get";
pub const CMD_MANAGER_START: &str = "manager_start";
pub const CMD_MANAGER_STOP: &str = "manager_stop";
pub const CMD_MANAGER_CLEAR_LOGS: &str = "manager_clear_logs";
pub const CMD_MANAGER_REVEAL_LOG_PATH: &str = "manager_reveal_log_path";
pub const CMD_MANAGER_SAVE: &str = "manager_save";
pub const CMD_MANAGER_APPLY_CHANNEL_ENV: &str = "manager_apply_channel_env";
pub const CMD_MANAGER_SEND: &str = "manager_send";
pub const CMD_MANAGER_OPEN_MCP_CONFIG: &str = "manager_open_mcp_config";
pub const CMD_MANAGER_OPEN_SKILL_DIR: &str = "manager_open_skill_dir";
pub const CMD_MANAGER_ADD_MCP: &str = "manager_add_mcp";
pub const CMD_MANAGER_CREATE_SKILL: &str = "manager_create_skill";
pub const CMD_MANAGER_LIST_SESSIONS: &str = "manager_list_sessions";
pub const CMD_MANAGER_USE_SESSION: &str = "manager_use_session";
pub const CMD_MANAGER_DELETE_SESSION: &str = "manager_delete_session";
pub const CMD_MANAGER_EXPORT_SESSION_HTML: &str = "manager_export_session_html";
