/**
 * Canonical Zod schema for GoalContractFields.
 *
 * Single source of truth for the constraints on a goal contract. Three callers
 * must agree on these rules:
 *   1. requirements/output-tools.ts register_goal — LLM produces a brand-new goal
 *   2. task-agent/tools.ts add_goal             — Task Agent inserts at runtime
 *   3. task-agent/tools.ts modify_goal           — Task Agent updates a subset
 *
 * Previously each call site re-declared its own schema (or none at all), which
 * meant add_goal could insert goals that violated the same min-length / enum
 * rules that register_goal enforced. This file collapses those into one schema.
 *
 * The TypeScript `GoalContractFields` interface in pipeline/types.ts intentionally
 * stays looser (e.g. `kind: string`) so existing call sites that pass through
 * runtime values from the database don't break. Validation happens at the
 * input boundaries (tool inputs) where strictness is meaningful.
 */
import { z } from "zod"

export const GOAL_KINDS = [
  "bootstrap",
  "feature",
  "verification",
  "integration",
  "system",
] as const

export const GOAL_PRIORITIES = ["blocking", "advisory"] as const

/**
 * Core fields, used directly by `register_goal` (LLM supplies id) and as the
 * base for `add_goal` (which omits id and supplies it via Identifier.ascending).
 */
export const GoalContractFieldsSchema = z.object({
  id: z
    .string()
    .min(1)
    .describe("Unique goal ID, e.g. goal_bootstrap, goal_api, goal_ui"),
  title: z.string().min(1).describe("Short human-readable goal title"),
  objective: z
    .string()
    .min(50)
    .describe(
      "Self-contained objective for an isolated executor. " +
        "Include: what to implement, key interfaces/types, expected behavior, edge cases.",
    ),
  done_definition: z
    .string()
    .min(10)
    .describe(
      "Concrete pass/fail criteria for Eval Agent. " +
        "Must be verifiable by running code, not vague.",
    ),
  owned_paths: z
    .array(z.string().min(1))
    .min(1)
    .describe(
      "Files this goal has EXCLUSIVE write access to. " +
        "Must be discovered via tool exploration — do not guess.",
    ),
  depends_on: z
    .array(z.string())
    .default([])
    .describe("Goal IDs this depends on (execution order)"),
  exports: z
    .array(z.string())
    .default([])
    .describe(
      "Interfaces this goal PROVIDES — function signatures, type definitions. " +
        "Dependent goals code against these.",
    ),
  imports: z
    .array(z.string())
    .default([])
    .describe("Interfaces this goal CONSUMES from dependencies"),
  priority: z.enum(GOAL_PRIORITIES).default("blocking"),
  kind: z.enum(GOAL_KINDS).default("feature"),
  requirement_ids: z
    .array(z.string())
    .default([])
    .describe("REQ-N references this goal covers"),
})

/**
 * Strict TypeScript type derived from the schema. Use at runtime input
 * boundaries; the looser `GoalContractFields` interface in pipeline/types.ts
 * stays the canonical type for downstream consumers.
 */
export type GoalContractFieldsParsed = z.infer<typeof GoalContractFieldsSchema>

/**
 * Schema for `add_goal` — id and requirement_ids are not LLM-supplied.
 * id is generated by `Identifier.ascending("goal")` and requirement_ids is
 * always [] for system-added goals.
 */
export const GoalContractAddInputSchema = GoalContractFieldsSchema.omit({
  id: true,
  requirement_ids: true,
})

export type GoalContractAddInput = z.infer<typeof GoalContractAddInputSchema>

/**
 * Schema for `modify_goal.updates` — every field optional, id excluded
 * (immutable), and constraints still enforced on whichever fields are
 * supplied. Use `.parse()` to reject invalid updates.
 */
export const GoalContractUpdateSchema = GoalContractFieldsSchema.omit({
  id: true,
}).partial()

export type GoalContractUpdate = z.infer<typeof GoalContractUpdateSchema>
