// Auto-generated by packages/opencorvus/script/generate-expert-squad-payload.ts. Do not edit.
import payload_algorithm_agents_architect_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/architect/system.md" with { type: "text" }
import payload_algorithm_agents_build_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/build/system.md" with { type: "text" }
import payload_algorithm_agents_coding_assistant_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/coding-assistant/system.md" with { type: "text" }
import payload_algorithm_agents_coding_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/coding/system.md" with { type: "text" }
import payload_algorithm_agents_deep_research_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/deep-research/system.md" with { type: "text" }
import payload_algorithm_agents_explore_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/explore/system.md" with { type: "text" }
import payload_algorithm_agents_fact_check_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/fact-check/system.md" with { type: "text" }
import payload_algorithm_agents_general_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/general/system.md" with { type: "text" }
import payload_algorithm_agents_goal_workload_analyst_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/goal-workload-analyst/system.md" with { type: "text" }
import payload_algorithm_agents_integrity_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/integrity/system.md" with { type: "text" }
import payload_algorithm_agents_intent_analysis_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/intent-analysis/system.md" with { type: "text" }
import payload_algorithm_agents_mission_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/mission/system.md" with { type: "text" }
import payload_algorithm_agents_orchestrator_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/orchestrator/system.md" with { type: "text" }
import payload_algorithm_agents_requirements_system_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/agents/requirements/system.md" with { type: "text" }
import payload_algorithm_expert_squad_jsonc from "../../../../.opencorvus/expert-squads/builtin/algorithm/expert-squad.jsonc" with { type: "text" }
import payload_algorithm_README_md from "../../../../.opencorvus/expert-squads/builtin/algorithm/README.md" with { type: "text" }
import payload_backend_agents_architect_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/architect/system.md" with { type: "text" }
import payload_backend_agents_build_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/build/system.md" with { type: "text" }
import payload_backend_agents_coding_assistant_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/coding-assistant/system.md" with { type: "text" }
import payload_backend_agents_coding_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/coding/system.md" with { type: "text" }
import payload_backend_agents_deep_research_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/deep-research/system.md" with { type: "text" }
import payload_backend_agents_explore_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/explore/system.md" with { type: "text" }
import payload_backend_agents_fact_check_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/fact-check/system.md" with { type: "text" }
import payload_backend_agents_general_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/general/system.md" with { type: "text" }
import payload_backend_agents_integrity_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/integrity/system.md" with { type: "text" }
import payload_backend_agents_intent_analysis_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/intent-analysis/system.md" with { type: "text" }
import payload_backend_agents_mission_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/mission/system.md" with { type: "text" }
import payload_backend_agents_orchestrator_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/orchestrator/system.md" with { type: "text" }
import payload_backend_agents_requirements_system_md from "../../../../.opencorvus/expert-squads/builtin/backend/agents/requirements/system.md" with { type: "text" }
import payload_backend_expert_squad_jsonc from "../../../../.opencorvus/expert-squads/builtin/backend/expert-squad.jsonc" with { type: "text" }
import payload_backend_README_md from "../../../../.opencorvus/expert-squads/builtin/backend/README.md" with { type: "text" }
import payload_frontend_automation_debug_agents_architect_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/architect/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_build_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/build/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_coding_assistant_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/coding-assistant/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_coding_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/coding/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_deep_research_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/deep-research/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_explore_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/explore/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_fact_check_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/fact-check/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_frontend_design_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/frontend-design/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_frontend_research_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/frontend-research/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_general_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/general/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_goal_workload_analyst_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/goal-workload-analyst/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_integrity_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/integrity/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_intent_analysis_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/intent-analysis/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_mission_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/mission/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_orchestrator_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/orchestrator/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_requirements_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/requirements/system.md" with { type: "text" }
import payload_frontend_automation_debug_agents_visual_qa_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/agents/visual-qa/system.md" with { type: "text" }
import payload_frontend_automation_debug_expert_squad_jsonc from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/expert-squad.jsonc" with { type: "text" }
import payload_frontend_automation_debug_README_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/README.md" with { type: "text" }
import payload_frontend_automation_debug_selector_md from "../../../../.opencorvus/expert-squads/builtin/frontend-automation-debug/selector.md" with { type: "text" }
import payload_frontend_innovate_agents_architect_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/architect/system.md" with { type: "text" }
import payload_frontend_innovate_agents_build_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/build/system.md" with { type: "text" }
import payload_frontend_innovate_agents_coding_assistant_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/coding-assistant/system.md" with { type: "text" }
import payload_frontend_innovate_agents_coding_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/coding/system.md" with { type: "text" }
import payload_frontend_innovate_agents_deep_research_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/deep-research/system.md" with { type: "text" }
import payload_frontend_innovate_agents_explore_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/explore/system.md" with { type: "text" }
import payload_frontend_innovate_agents_fact_check_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/fact-check/system.md" with { type: "text" }
import payload_frontend_innovate_agents_frontend_design_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/frontend-design/system.md" with { type: "text" }
import payload_frontend_innovate_agents_frontend_research_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/frontend-research/system.md" with { type: "text" }
import payload_frontend_innovate_agents_general_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/general/system.md" with { type: "text" }
import payload_frontend_innovate_agents_goal_workload_analyst_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/goal-workload-analyst/system.md" with { type: "text" }
import payload_frontend_innovate_agents_integrity_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/integrity/system.md" with { type: "text" }
import payload_frontend_innovate_agents_intent_analysis_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/intent-analysis/system.md" with { type: "text" }
import payload_frontend_innovate_agents_mission_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/mission/system.md" with { type: "text" }
import payload_frontend_innovate_agents_orchestrator_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/orchestrator/system.md" with { type: "text" }
import payload_frontend_innovate_agents_requirements_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/requirements/system.md" with { type: "text" }
import payload_frontend_innovate_agents_visual_qa_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/agents/visual-qa/system.md" with { type: "text" }
import payload_frontend_innovate_expert_squad_jsonc from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/expert-squad.jsonc" with { type: "text" }
import payload_frontend_innovate_README_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/README.md" with { type: "text" }
import payload_frontend_innovate_selector_md from "../../../../.opencorvus/expert-squads/builtin/frontend-innovate/selector.md" with { type: "text" }
import payload_frontend_replica_agents_architect_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/architect/system.md" with { type: "text" }
import payload_frontend_replica_agents_build_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/build/system.md" with { type: "text" }
import payload_frontend_replica_agents_coding_assistant_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/coding-assistant/system.md" with { type: "text" }
import payload_frontend_replica_agents_coding_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/coding/system.md" with { type: "text" }
import payload_frontend_replica_agents_explore_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/explore/system.md" with { type: "text" }
import payload_frontend_replica_agents_frontend_design_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/frontend-design/system.md" with { type: "text" }
import payload_frontend_replica_agents_frontend_research_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/frontend-research/system.md" with { type: "text" }
import payload_frontend_replica_agents_general_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/general/system.md" with { type: "text" }
import payload_frontend_replica_agents_integrity_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/integrity/system.md" with { type: "text" }
import payload_frontend_replica_agents_intent_analysis_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/intent-analysis/system.md" with { type: "text" }
import payload_frontend_replica_agents_mission_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/mission/system.md" with { type: "text" }
import payload_frontend_replica_agents_orchestrator_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/orchestrator/system.md" with { type: "text" }
import payload_frontend_replica_agents_requirements_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/requirements/system.md" with { type: "text" }
import payload_frontend_replica_agents_visual_qa_system_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/agents/visual-qa/system.md" with { type: "text" }
import payload_frontend_replica_expert_squad_jsonc from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/expert-squad.jsonc" with { type: "text" }
import payload_frontend_replica_README_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/README.md" with { type: "text" }
import payload_frontend_replica_selector_md from "../../../../.opencorvus/expert-squads/builtin/frontend-replica/selector.md" with { type: "text" }
import payload_opentest_agents_orchestrator_skills_workflow_SKILL_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/agents/orchestrator/skills/workflow/SKILL.md" with { type: "text" }
import payload_opentest_agents_orchestrator_system_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/agents/orchestrator/system.md" with { type: "text" }
import payload_opentest_expert_squad_jsonc from "../../../../.opencorvus/expert-squads/wujiang/opentest/expert-squad.jsonc" with { type: "text" }
import payload_opentest_protocol_engine_opentest_contract_json from "../../../../.opencorvus/expert-squads/wujiang/opentest/protocol-engine/opentest-contract.json" with { type: "text" }
import payload_opentest_protocol_engine_opentest_protocol_engine_ts from "../../../../.opencorvus/expert-squads/wujiang/opentest/protocol-engine/opentest-protocol-engine.ts" with { type: "text" }
import payload_opentest_README_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/README.md" with { type: "text" }
import payload_opentest_selector_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/selector.md" with { type: "text" }
import payload_opentest_tools_opentest_protocol_engine_ts from "../../../../.opencorvus/expert-squads/wujiang/opentest/tools/opentest-protocol-engine.ts" with { type: "text" }
import payload_opentest_virtual_agents_architect_skills_test_architecture_SKILL_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/virtual-agents/architect/skills/test-architecture/SKILL.md" with { type: "text" }
import payload_opentest_virtual_agents_architect_system_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/virtual-agents/architect/system.md" with { type: "text" }
import payload_opentest_virtual_agents_build_skills_test_implementation_SKILL_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/virtual-agents/build/skills/test-implementation/SKILL.md" with { type: "text" }
import payload_opentest_virtual_agents_build_system_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/virtual-agents/build/system.md" with { type: "text" }
import payload_opentest_virtual_agents_integrity_skills_test_review_SKILL_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/virtual-agents/integrity/skills/test-review/SKILL.md" with { type: "text" }
import payload_opentest_virtual_agents_integrity_system_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/virtual-agents/integrity/system.md" with { type: "text" }
import payload_opentest_virtual_agents_requirements_skills_test_requirements_SKILL_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/virtual-agents/requirements/skills/test-requirements/SKILL.md" with { type: "text" }
import payload_opentest_virtual_agents_requirements_system_md from "../../../../.opencorvus/expert-squads/wujiang/opentest/virtual-agents/requirements/system.md" with { type: "text" }

import type { ExpertSquadRegistry } from "./registry"

const textPayload = (value: unknown): string => value as string

export const payloadPackageSources: readonly ExpertSquadRegistry.EmbeddedPackageSource[] = [
  {
    namespace: "builtin",
    id: "algorithm",
    manifestText: textPayload(payload_algorithm_expert_squad_jsonc),
    files: {
      "agents/architect/system.md": textPayload(payload_algorithm_agents_architect_system_md),
      "agents/build/system.md": textPayload(payload_algorithm_agents_build_system_md),
      "agents/coding-assistant/system.md": textPayload(payload_algorithm_agents_coding_assistant_system_md),
      "agents/coding/system.md": textPayload(payload_algorithm_agents_coding_system_md),
      "agents/deep-research/system.md": textPayload(payload_algorithm_agents_deep_research_system_md),
      "agents/explore/system.md": textPayload(payload_algorithm_agents_explore_system_md),
      "agents/fact-check/system.md": textPayload(payload_algorithm_agents_fact_check_system_md),
      "agents/general/system.md": textPayload(payload_algorithm_agents_general_system_md),
      "agents/goal-workload-analyst/system.md": textPayload(payload_algorithm_agents_goal_workload_analyst_system_md),
      "agents/integrity/system.md": textPayload(payload_algorithm_agents_integrity_system_md),
      "agents/intent-analysis/system.md": textPayload(payload_algorithm_agents_intent_analysis_system_md),
      "agents/mission/system.md": textPayload(payload_algorithm_agents_mission_system_md),
      "agents/orchestrator/system.md": textPayload(payload_algorithm_agents_orchestrator_system_md),
      "agents/requirements/system.md": textPayload(payload_algorithm_agents_requirements_system_md),
      "expert-squad.jsonc": textPayload(payload_algorithm_expert_squad_jsonc),
      "README.md": textPayload(payload_algorithm_README_md),
    },
  },
  {
    namespace: "builtin",
    id: "backend",
    manifestText: textPayload(payload_backend_expert_squad_jsonc),
    files: {
      "agents/architect/system.md": textPayload(payload_backend_agents_architect_system_md),
      "agents/build/system.md": textPayload(payload_backend_agents_build_system_md),
      "agents/coding-assistant/system.md": textPayload(payload_backend_agents_coding_assistant_system_md),
      "agents/coding/system.md": textPayload(payload_backend_agents_coding_system_md),
      "agents/deep-research/system.md": textPayload(payload_backend_agents_deep_research_system_md),
      "agents/explore/system.md": textPayload(payload_backend_agents_explore_system_md),
      "agents/fact-check/system.md": textPayload(payload_backend_agents_fact_check_system_md),
      "agents/general/system.md": textPayload(payload_backend_agents_general_system_md),
      "agents/integrity/system.md": textPayload(payload_backend_agents_integrity_system_md),
      "agents/intent-analysis/system.md": textPayload(payload_backend_agents_intent_analysis_system_md),
      "agents/mission/system.md": textPayload(payload_backend_agents_mission_system_md),
      "agents/orchestrator/system.md": textPayload(payload_backend_agents_orchestrator_system_md),
      "agents/requirements/system.md": textPayload(payload_backend_agents_requirements_system_md),
      "expert-squad.jsonc": textPayload(payload_backend_expert_squad_jsonc),
      "README.md": textPayload(payload_backend_README_md),
    },
  },
  {
    namespace: "builtin",
    id: "frontend-automation-debug",
    manifestText: textPayload(payload_frontend_automation_debug_expert_squad_jsonc),
    files: {
      "agents/architect/system.md": textPayload(payload_frontend_automation_debug_agents_architect_system_md),
      "agents/build/system.md": textPayload(payload_frontend_automation_debug_agents_build_system_md),
      "agents/coding-assistant/system.md": textPayload(payload_frontend_automation_debug_agents_coding_assistant_system_md),
      "agents/coding/system.md": textPayload(payload_frontend_automation_debug_agents_coding_system_md),
      "agents/deep-research/system.md": textPayload(payload_frontend_automation_debug_agents_deep_research_system_md),
      "agents/explore/system.md": textPayload(payload_frontend_automation_debug_agents_explore_system_md),
      "agents/fact-check/system.md": textPayload(payload_frontend_automation_debug_agents_fact_check_system_md),
      "agents/frontend-design/system.md": textPayload(payload_frontend_automation_debug_agents_frontend_design_system_md),
      "agents/frontend-research/system.md": textPayload(payload_frontend_automation_debug_agents_frontend_research_system_md),
      "agents/general/system.md": textPayload(payload_frontend_automation_debug_agents_general_system_md),
      "agents/goal-workload-analyst/system.md": textPayload(payload_frontend_automation_debug_agents_goal_workload_analyst_system_md),
      "agents/integrity/system.md": textPayload(payload_frontend_automation_debug_agents_integrity_system_md),
      "agents/intent-analysis/system.md": textPayload(payload_frontend_automation_debug_agents_intent_analysis_system_md),
      "agents/mission/system.md": textPayload(payload_frontend_automation_debug_agents_mission_system_md),
      "agents/orchestrator/system.md": textPayload(payload_frontend_automation_debug_agents_orchestrator_system_md),
      "agents/requirements/system.md": textPayload(payload_frontend_automation_debug_agents_requirements_system_md),
      "agents/visual-qa/system.md": textPayload(payload_frontend_automation_debug_agents_visual_qa_system_md),
      "expert-squad.jsonc": textPayload(payload_frontend_automation_debug_expert_squad_jsonc),
      "README.md": textPayload(payload_frontend_automation_debug_README_md),
      "selector.md": textPayload(payload_frontend_automation_debug_selector_md),
    },
  },
  {
    namespace: "builtin",
    id: "frontend-innovate",
    manifestText: textPayload(payload_frontend_innovate_expert_squad_jsonc),
    files: {
      "agents/architect/system.md": textPayload(payload_frontend_innovate_agents_architect_system_md),
      "agents/build/system.md": textPayload(payload_frontend_innovate_agents_build_system_md),
      "agents/coding-assistant/system.md": textPayload(payload_frontend_innovate_agents_coding_assistant_system_md),
      "agents/coding/system.md": textPayload(payload_frontend_innovate_agents_coding_system_md),
      "agents/deep-research/system.md": textPayload(payload_frontend_innovate_agents_deep_research_system_md),
      "agents/explore/system.md": textPayload(payload_frontend_innovate_agents_explore_system_md),
      "agents/fact-check/system.md": textPayload(payload_frontend_innovate_agents_fact_check_system_md),
      "agents/frontend-design/system.md": textPayload(payload_frontend_innovate_agents_frontend_design_system_md),
      "agents/frontend-research/system.md": textPayload(payload_frontend_innovate_agents_frontend_research_system_md),
      "agents/general/system.md": textPayload(payload_frontend_innovate_agents_general_system_md),
      "agents/goal-workload-analyst/system.md": textPayload(payload_frontend_innovate_agents_goal_workload_analyst_system_md),
      "agents/integrity/system.md": textPayload(payload_frontend_innovate_agents_integrity_system_md),
      "agents/intent-analysis/system.md": textPayload(payload_frontend_innovate_agents_intent_analysis_system_md),
      "agents/mission/system.md": textPayload(payload_frontend_innovate_agents_mission_system_md),
      "agents/orchestrator/system.md": textPayload(payload_frontend_innovate_agents_orchestrator_system_md),
      "agents/requirements/system.md": textPayload(payload_frontend_innovate_agents_requirements_system_md),
      "agents/visual-qa/system.md": textPayload(payload_frontend_innovate_agents_visual_qa_system_md),
      "expert-squad.jsonc": textPayload(payload_frontend_innovate_expert_squad_jsonc),
      "README.md": textPayload(payload_frontend_innovate_README_md),
      "selector.md": textPayload(payload_frontend_innovate_selector_md),
    },
  },
  {
    namespace: "builtin",
    id: "frontend-replica",
    manifestText: textPayload(payload_frontend_replica_expert_squad_jsonc),
    files: {
      "agents/architect/system.md": textPayload(payload_frontend_replica_agents_architect_system_md),
      "agents/build/system.md": textPayload(payload_frontend_replica_agents_build_system_md),
      "agents/coding-assistant/system.md": textPayload(payload_frontend_replica_agents_coding_assistant_system_md),
      "agents/coding/system.md": textPayload(payload_frontend_replica_agents_coding_system_md),
      "agents/explore/system.md": textPayload(payload_frontend_replica_agents_explore_system_md),
      "agents/frontend-design/system.md": textPayload(payload_frontend_replica_agents_frontend_design_system_md),
      "agents/frontend-research/system.md": textPayload(payload_frontend_replica_agents_frontend_research_system_md),
      "agents/general/system.md": textPayload(payload_frontend_replica_agents_general_system_md),
      "agents/integrity/system.md": textPayload(payload_frontend_replica_agents_integrity_system_md),
      "agents/intent-analysis/system.md": textPayload(payload_frontend_replica_agents_intent_analysis_system_md),
      "agents/mission/system.md": textPayload(payload_frontend_replica_agents_mission_system_md),
      "agents/orchestrator/system.md": textPayload(payload_frontend_replica_agents_orchestrator_system_md),
      "agents/requirements/system.md": textPayload(payload_frontend_replica_agents_requirements_system_md),
      "agents/visual-qa/system.md": textPayload(payload_frontend_replica_agents_visual_qa_system_md),
      "expert-squad.jsonc": textPayload(payload_frontend_replica_expert_squad_jsonc),
      "README.md": textPayload(payload_frontend_replica_README_md),
      "selector.md": textPayload(payload_frontend_replica_selector_md),
    },
  },
  {
    namespace: "wujiang",
    id: "opentest",
    manifestText: textPayload(payload_opentest_expert_squad_jsonc),
    files: {
      "agents/orchestrator/skills/workflow/SKILL.md": textPayload(payload_opentest_agents_orchestrator_skills_workflow_SKILL_md),
      "agents/orchestrator/system.md": textPayload(payload_opentest_agents_orchestrator_system_md),
      "expert-squad.jsonc": textPayload(payload_opentest_expert_squad_jsonc),
      "protocol-engine/opentest-contract.json": textPayload(payload_opentest_protocol_engine_opentest_contract_json),
      "protocol-engine/opentest-protocol-engine.ts": textPayload(payload_opentest_protocol_engine_opentest_protocol_engine_ts),
      "README.md": textPayload(payload_opentest_README_md),
      "selector.md": textPayload(payload_opentest_selector_md),
      "tools/opentest-protocol-engine.ts": textPayload(payload_opentest_tools_opentest_protocol_engine_ts),
      "virtual-agents/architect/skills/test-architecture/SKILL.md": textPayload(payload_opentest_virtual_agents_architect_skills_test_architecture_SKILL_md),
      "virtual-agents/architect/system.md": textPayload(payload_opentest_virtual_agents_architect_system_md),
      "virtual-agents/build/skills/test-implementation/SKILL.md": textPayload(payload_opentest_virtual_agents_build_skills_test_implementation_SKILL_md),
      "virtual-agents/build/system.md": textPayload(payload_opentest_virtual_agents_build_system_md),
      "virtual-agents/integrity/skills/test-review/SKILL.md": textPayload(payload_opentest_virtual_agents_integrity_skills_test_review_SKILL_md),
      "virtual-agents/integrity/system.md": textPayload(payload_opentest_virtual_agents_integrity_system_md),
      "virtual-agents/requirements/skills/test-requirements/SKILL.md": textPayload(payload_opentest_virtual_agents_requirements_skills_test_requirements_SKILL_md),
      "virtual-agents/requirements/system.md": textPayload(payload_opentest_virtual_agents_requirements_system_md),
    },
  },
]
