import path from "path"

type Dict = Record<string, string>
type Out = {
  file: string
  text: string
}

const root = process.cwd()
const src = path.join(root, "packages", "overlay", "protocol", "schema.json")
const schema = await Bun.file(src).json()
const check = process.argv.includes("--check")

function table(input: unknown, name: string) {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    throw new Error(`invalid ${name}: expected object`)
  }
  const out: Dict = {}
  for (const [key, value] of Object.entries(input as Record<string, unknown>)) {
    if (typeof value !== "string" || !value.trim()) {
      throw new Error(`invalid ${name}.${key}: expected non-empty string`)
    }
    out[key] = value
  }
  return out
}

const windows = table((schema as Record<string, unknown>).windows, "windows")
const events = table((schema as Record<string, unknown>).events, "events")
const messages = table((schema as Record<string, unknown>).messages, "messages")
const commands = table((schema as Record<string, unknown>).commands, "commands")

function upper(input: string) {
  return input
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase()
}

function object(items: Dict, indent: string) {
  return Object.entries(items)
    .map(([key, value]) => `${indent}${key}: "${value}",`)
    .join("\n")
}

function rust(items: Dict, prefix: string) {
  return Object.entries(items)
    .map(([key, value]) => `pub const ${prefix}_${upper(key)}: &str = "${value}";`)
    .join("\n")
}

const ts = `// Generated by scripts/generate-overlay-protocol.ts. Do not edit manually.
export const overlayProtocol = {
  windows: {
${object(windows, "    ")}
  },
  events: {
${object(events, "    ")}
  },
  messages: {
${object(messages, "    ")}
  },
  commands: {
${object(commands, "    ")}
  },
} as const
`

const js = `// Generated by scripts/generate-overlay-protocol.ts. Do not edit manually.
;(function () {
  const protocol = Object.freeze({
    windows: Object.freeze({
${object(windows, "      ")}
    }),
    events: Object.freeze({
${object(events, "      ")}
    }),
    messages: Object.freeze({
${object(messages, "      ")}
    }),
    commands: Object.freeze({
${object(commands, "      ")}
    }),
  })
  window.opencorvusOverlayProtocol = protocol
})()
`

const rs = `// Generated by scripts/generate-overlay-protocol.ts. Do not edit manually.
#![allow(dead_code)]
${rust(windows, "WINDOW")}

${rust(events, "EVT")}

${rust(messages, "MSG")}

${rust(commands, "CMD")}
`

const out: Out[] = [
  {
    file: path.join(root, "packages", "opencorvus", "src", "tool", "overlay-protocol.ts"),
    text: ts,
  },
  {
    file: path.join(root, "packages", "overlay", "src", "protocol.js"),
    text: js,
  },
  {
    file: path.join(root, "packages", "overlay", "src-tauri", "src", "events.rs"),
    text: rs,
  },
]

if (check) {
  const stale: string[] = []
  for (const item of out) {
    const file = Bun.file(item.file)
    const text = (await file.exists()) ? await file.text() : ""
    if (text === item.text) continue
    stale.push(item.file)
  }
  if (stale.length === 0) {
    console.log("overlay protocol is up to date")
    process.exit(0)
  }
  console.error("overlay protocol is stale:")
  for (const file of stale) console.error(` - ${file}`)
  console.error("run: bun run scripts/generate-overlay-protocol.ts")
  process.exit(1)
}

for (const item of out) await Bun.write(item.file, item.text)
console.log("overlay protocol generated")
