// Generated by scripts/generate-overlay-protocol.ts. Do not edit manually.
;(function () {
  const protocol = Object.freeze({
    windows: Object.freeze({
      overlay: "overlay",
      highlight: "window-highlight",
      confirm: "confirm",
      console: "console",
    }),
    events: Object.freeze({
      showOverlay: "show-overlay",
      showConfirm: "show-confirm",
      showWindowHighlight: "show-window-highlight",
      managerLog: "manager-log",
      managerState: "manager-state",
      managerChat: "manager-chat",
      overlayDiagnostic: "overlay-diagnostic",
    }),
    messages: Object.freeze({
      hint: "hint",
      confirm: "confirm",
      windowHighlight: "window-highlight",
      diagnostic: "diagnostic",
      confirmReply: "confirm-reply",
    }),
    commands: Object.freeze({
      positionWindow: "position_window",
      hideWindow: "hide_window",
      confirmReply: "confirm_reply",
      managerOpen: "manager_open",
      managerGet: "manager_get",
      managerStart: "manager_start",
      managerStop: "manager_stop",
      managerClearLogs: "manager_clear_logs",
      managerSave: "manager_save",
      managerSend: "manager_send",
      managerOpenMcpConfig: "manager_open_mcp_config",
      managerOpenSkillDir: "manager_open_skill_dir",
      managerAddMcp: "manager_add_mcp",
      managerCreateSkill: "manager_create_skill",
    }),
  })
  window.opencorvusOverlayProtocol = protocol
})()
