/**
 * ProjectScaffold → codegen-artifact emitters.
 *
 *   - `scaffoldToPlan(scaffold) → PlanFile[]` — feeds the codegen agent's
 *     per-file plan (tier-graph orders these for parallel codegen).
 *   - `generateTokensFile(scaffold) → GeneratedFile` — pre-built
 *     `design-tokens.ts` with COLORS / FONTS / SPACING / RADII / CSS_VARS.
 *   - `generateAppFile(scaffold) → GeneratedFile` — pre-built `App.tsx`
 *     composing every section.
 *   - `buildSharedContext(scaffold, meta) → string` — compact prompt-ready
 *     token + pattern summary (2-5KB vs 50-200KB raw XML).
 *
 * Originally `mirror/url/pattern/scaffold.ts` — promoted to `shared/` when
 * image2code joined as a third source whose `analyze` step needs the same
 * helpers (rule 22 single source). The functions are pure on
 * `ProjectScaffold` and never reference URL-, Figma-, or image-specific
 * fields, which is why a single shared module is the right home.
 *
 * No cross-module imports inside `mirror/` — depends only on `ir/scaffold`.
 *
 * Zero LLM, deterministic.
 */

import type {
  ComponentCatalog as _ComponentCatalog,
  DesignTokenSystem as _DesignTokenSystem,
  FileContract,
  GeneratedFile,
  PlanFile,
  ProjectScaffold,
  SectionContract as _SectionContract,
  TokenColor,
} from "../ir/scaffold"

// ─── Scaffold → PlanFile[] ───────────────────────────────────────────────

/**
 * Order: shared components → sections (top-to-bottom, sub-components first) →
 * tokens + App.tsx **excluded** (they're pre-generated deterministically).
 */
export function scaffoldToPlan(scaffold: ProjectScaffold): PlanFile[] {
  const plan: PlanFile[] = []

  for (const fc of scaffold.sharedComponents) {
    plan.push(fileContractToPlanFile(fc, "shared"))
  }

  for (const sec of scaffold.sections) {
    for (const sub of sec.subComponents) {
      plan.push(fileContractToPlanFile(sub, `section:${sec.name}`))
    }
    plan.push(fileContractToPlanFile(sec.file, `section:${sec.name}`))
  }

  return plan
}

function fileContractToPlanFile(fc: FileContract, source: string): PlanFile {
  const notesParts: string[] = []

  if (fc.sectionIR) {
    notesParts.push("## 结构描述 (XML IR)\n\n" + fc.sectionIR)
  }

  if (fc.propsInterface) {
    notesParts.push("## Props 接口\n\n```typescript\n" + fc.propsInterface + "\n```")
  }

  if (fc.patterns.length > 0) {
    notesParts.push("## 使用的共享组件\n\n" + fc.patterns.map((p) => `- ${p}`).join("\n"))
  }

  return {
    file_path: fc.filePath,
    file_info: `${fc.exportName} component (${source})`,
    notes: notesParts.join("\n\n"),
    contracts: {
      exports: [fc.exportName],
      types: fc.propsInterface || undefined,
      imports: Object.keys(fc.imports).length > 0 ? fc.imports : undefined,
    },
  }
}

// ─── Pre-generated deterministic files ───────────────────────────────────

function colorVarName(c: TokenColor): string {
  if (c.semantic) return c.semantic.replace(/-/g, "_")
  return c.value
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase()
}

/** `design-tokens.ts` as a `GeneratedFile` — emits COLORS/FONTS/SPACING/RADII/CSS_VARS consts. */
export function generateTokensFile(scaffold: ProjectScaffold): GeneratedFile {
  const tokens = scaffold.tokens
  const lines: string[] = [
    "// Design tokens extracted from the original page",
    "// Auto-generated by Mirror pattern extraction (deterministic, zero LLM)",
    "",
  ]

  if (tokens.colors.length > 0) {
    lines.push("export const COLORS = {")
    const usedColorNames = new Set<string>()
    for (const c of tokens.colors) {
      let name = colorVarName(c)
      if (usedColorNames.has(name)) {
        for (let i = 2; i < 100; i++) {
          const candidate = `${name}_${i}`
          if (!usedColorNames.has(candidate)) {
            name = candidate
            break
          }
        }
      }
      usedColorNames.add(name)
      const semantic = c.semantic ? ` // ${c.semantic}, freq: ${c.frequency}` : ` // freq: ${c.frequency}`
      lines.push(`  ${name}: "${c.value}",${semantic}`)
    }
    lines.push("} as const", "")
  }

  const ICON_FONT_PATTERNS =
    /^(c?iconfont|cos-icon|fontawesome|material[- ]?icons|glyphicons|ionicons|feather|remixicon|bootstrap-icons|anticon)/i
  const textFonts = tokens.fonts.filter((f) => !ICON_FONT_PATTERNS.test(f.family))
  if (textFonts.length > 0) {
    lines.push("export const FONTS = {")
    for (const f of textFonts) {
      const name = f.family
        .replace(/[^a-zA-Z0-9]+/g, "_")
        .replace(/^_|_$/g, "")
        .toLowerCase()
      lines.push(`  ${name}: "${f.family}",`)
    }
    lines.push("} as const", "")
  }

  if (tokens.spacing.length > 0) {
    lines.push("export const SPACING = {")
    for (const s of tokens.spacing) {
      const tw = s.tailwind ? ` // tw: ${s.tailwind}` : ""
      lines.push(`  sp${s.px}: ${s.px},${tw}`)
    }
    lines.push("} as const", "")
  }

  if (tokens.radii.length > 0) {
    lines.push("export const RADII = {")
    for (const r of tokens.radii) {
      const tw = r.tailwind ? ` // tw: rounded-${r.tailwind}` : ""
      lines.push(`  r${r.px}: ${r.px},${tw}`)
    }
    lines.push("} as const", "")
  }

  const NOISE_PREFIXES = [
    "--shiki",
    "--toastify",
    "--tw-",
    "--rt-",
    "--Colors-",
    "--Bg-",
    "--BgGp-",
    "--Labels-",
    "--Fills-",
    "--Separators-",
    "--MaskBg-",
    "--Always-",
    "--Others",
    "--Syntax-",
    "--UI-",
    "--markdown-",
  ]
  const customProps = Object.entries(tokens.customProperties).filter(
    ([key]) => !NOISE_PREFIXES.some((prefix) => key.startsWith(prefix)),
  )
  if (customProps.length > 0) {
    lines.push("export const CSS_VARS = {")
    for (const [key, value] of customProps) {
      let name = key.replace(/^--/, "").replace(/-([a-z])/g, (_, c) => c.toUpperCase())
      if (/[^a-zA-Z0-9_$]/.test(name)) name = `"${name}"`
      const safeValue = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
      lines.push(`  ${name}: "${safeValue}",`)
    }
    lines.push("} as const", "")
  }

  return {
    file_path: scaffold.tokensFile.filePath,
    code: lines.join("\n"),
  }
}

/** `App.tsx` as a `GeneratedFile` — imports and composes all sections. */
export function generateAppFile(scaffold: ProjectScaffold): GeneratedFile {
  const imports: string[] = ['import React from "react"']
  const components: string[] = []

  for (const sec of scaffold.sections) {
    const importPath =
      "./" +
      sec.file.filePath.replace(/^packages\/app\/src\//, "").replace(/\.tsx$/, "")
    imports.push(`import { ${sec.file.exportName} } from "${importPath}"`)
    components.push(`      <${sec.file.exportName} />`)
  }

  const code = `${imports.join("\n")}

export function App() {
  return (
    <div className="min-h-screen">
${components.join("\n")}
    </div>
  )
}
`

  return {
    file_path: scaffold.appFile.filePath,
    code,
  }
}

// ─── Shared context builder ──────────────────────────────────────────────

/** Source-agnostic page metadata for the shared-context preamble.
 *  `url` is optional because image2code clones have no upstream URL. */
export interface SharedContextMeta {
  url?: string
  title: string
  viewport: { width: number; height: number }
}

/**
 * Compact context string to inject into codegen prompts — includes page
 * metadata + token summary + detected-component summary. 2-5KB vs
 * 50-200KB for raw XML dump.
 */
export function buildSharedContext(
  scaffold: ProjectScaffold,
  meta: SharedContextMeta,
): string {
  const parts: string[] = []

  const headerBits: string[] = [`Page: ${meta.title}`]
  if (meta.url) headerBits.push(`URL: ${meta.url}`)
  headerBits.push(`Viewport: ${meta.viewport.width}x${meta.viewport.height}`)
  parts.push(`<!-- ${headerBits.join(" | ")} -->`)

  const t = scaffold.tokens
  if (t.colors.length > 0) {
    parts.push("\n## 设计 Token — 颜色")
    for (const c of t.colors.slice(0, 15)) {
      const sem = c.semantic ? ` (${c.semantic})` : ""
      parts.push(`- \`${c.value}\`${sem} — 使用 ${c.frequency} 次`)
    }
  }
  if (t.fonts.length > 0) {
    parts.push("\n## 设计 Token — 字体")
    for (const f of t.fonts) {
      parts.push(`- ${f.family}: weights [${f.weights.join(", ")}], sizes [${f.sizes.join(", ")}px]`)
    }
  }
  if (t.spacing.length > 0) {
    parts.push("\n## 设计 Token — 间距")
    const topSpacing = t.spacing.slice(0, 8)
    parts.push(
      `常用间距: ${topSpacing.map((s) => `${s.px}px${s.tailwind ? `(tw:${s.tailwind})` : ""}`).join(", ")}`,
    )
  }

  const catalog = scaffold.catalog
  if (catalog.patterns.length > 0) {
    parts.push("\n## 检测到的可复用组件模式")
    for (const p of catalog.patterns) {
      const propsDesc =
        p.props.length > 0
          ? ` — props: ${p.props.map((pr) => `${pr.name}: ${pr.type}`).join(", ")}`
          : ""
      parts.push(
        `- **${p.name}** (${p.instanceCount} 个实例, 相似度 ${(p.structuralSimilarity * 100).toFixed(0)}%)${propsDesc}`,
      )
    }
    parts.push(
      `\n覆盖率: ${catalog.coveredElements}/${catalog.totalElements} 元素 (${((catalog.coveredElements / Math.max(catalog.totalElements, 1)) * 100).toFixed(0)}%)`,
    )
  }

  return parts.join("\n")
}
