/**
 * Goal delivery merge strategies.
 *
 * Handles merging per-goal deliveries back to the main workspace:
 * - owned_paths validation: checks files are within goal's declared scope
 * - Shared file merging: JSON deep-merge for package.json, tsconfig.json
 * - Conflict detection: flags files modified by multiple concurrent goals
 */
import { Log } from "@/util/log"

const log = Log.create({ service: "goal-merge" })

// ── owned_paths validation ──

export interface ValidationResult {
  valid: boolean
  violations: string[]
}

/**
 * Check if all modified files are within the goal's declared owned_paths.
 * Returns violations (files outside scope). Empty owned_paths = no constraint.
 */
export function validateOwnedPaths(
  modifiedFiles: string[],
  ownedPaths: string[],
): ValidationResult {
  if (ownedPaths.length === 0) return { valid: true, violations: [] }
  const violations = modifiedFiles.filter(
    (file) => !ownedPaths.some((p) => file === p || file.startsWith(p + "/") || isSharedFile(file)),
  )
  return { valid: violations.length === 0, violations }
}

// ── Shared file detection ──

const SHARED_FILES = new Set([
  "package.json",
  "tsconfig.json",
  "bun.lock",
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
])

/** Returns true if the file is a known shared/infrastructure file that multiple goals may touch. */
export function isSharedFile(file: string): boolean {
  const basename = file.split("/").pop() ?? file
  return SHARED_FILES.has(basename)
}

// ── JSON deep merge ──

export interface MergeResult {
  content: string
  conflict: boolean
  reason?: string
}

/**
 * Deep-merge two versions of package.json.
 * - dependencies/devDependencies: union (both versions' deps included)
 * - scripts: union, conflict if same key with different values
 * - other fields: incoming wins
 */
export function mergePackageJson(existing: string, incoming: string): MergeResult {
  try {
    const base = JSON.parse(existing || "{}")
    const next = JSON.parse(incoming || "{}")

    // Merge dependencies
    base.dependencies = { ...(base.dependencies ?? {}), ...(next.dependencies ?? {}) }
    base.devDependencies = { ...(base.devDependencies ?? {}), ...(next.devDependencies ?? {}) }

    // Merge scripts — detect conflicts
    const conflicts: string[] = []
    if (next.scripts) {
      base.scripts = base.scripts ?? {}
      for (const [key, value] of Object.entries(next.scripts)) {
        if (base.scripts[key] && base.scripts[key] !== value) {
          conflicts.push(`scripts.${key}: "${base.scripts[key]}" vs "${value}"`)
        }
        base.scripts[key] = value
      }
    }

    // Other top-level fields: incoming wins
    for (const [key, value] of Object.entries(next)) {
      if (key === "dependencies" || key === "devDependencies" || key === "scripts") continue
      base[key] = value
    }

    if (conflicts.length > 0) {
      log.warn("package.json merge: script conflicts resolved (incoming wins)", { conflicts })
    }

    return { content: JSON.stringify(base, null, 2) + "\n", conflict: false }
  } catch (err) {
    return { content: incoming, conflict: true, reason: `JSON parse error: ${err}` }
  }
}

/**
 * Deep-merge two versions of tsconfig.json.
 * - compilerOptions: union
 * - include/exclude: union arrays
 * - other fields: incoming wins
 */
export function mergeTsConfig(existing: string, incoming: string): MergeResult {
  try {
    const base = JSON.parse(existing || "{}")
    const next = JSON.parse(incoming || "{}")

    // Merge compilerOptions
    base.compilerOptions = { ...(base.compilerOptions ?? {}), ...(next.compilerOptions ?? {}) }

    // Merge include/exclude arrays
    if (next.include) {
      base.include = [...new Set([...(base.include ?? []), ...next.include])]
    }
    if (next.exclude) {
      base.exclude = [...new Set([...(base.exclude ?? []), ...next.exclude])]
    }

    // Other fields: incoming wins
    for (const [key, value] of Object.entries(next)) {
      if (key === "compilerOptions" || key === "include" || key === "exclude") continue
      base[key] = value
    }

    return { content: JSON.stringify(base, null, 2) + "\n", conflict: false }
  } catch (err) {
    return { content: incoming, conflict: true, reason: `JSON parse error: ${err}` }
  }
}

/**
 * Get the appropriate merge function for a shared file.
 * Returns undefined for non-shared files (direct write).
 * Returns "skip" for lockfiles (regenerated by package manager).
 */
export function getMerger(file: string): ((existing: string, incoming: string) => MergeResult) | "skip" | undefined {
  const basename = file.split("/").pop() ?? file
  if (basename === "package.json") return mergePackageJson
  if (basename === "tsconfig.json") return mergeTsConfig
  if (basename === "bun.lock" || basename === "package-lock.json" || basename === "pnpm-lock.yaml" || basename === "yarn.lock") return "skip"
  return undefined
}
